/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	apipolicieskyvernoiov1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	versioned "github.com/kyverno/kyverno/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kyverno/kyverno/pkg/client/informers/externalversions/internalinterfaces"
	policieskyvernoiov1beta1 "github.com/kyverno/kyverno/pkg/client/listers/policies.kyverno.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NamespacedValidatingPolicyInformer provides access to a shared informer and lister for
// NamespacedValidatingPolicies.
type NamespacedValidatingPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() policieskyvernoiov1beta1.NamespacedValidatingPolicyLister
}

type namespacedValidatingPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNamespacedValidatingPolicyInformer constructs a new informer for NamespacedValidatingPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNamespacedValidatingPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNamespacedValidatingPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNamespacedValidatingPolicyInformer constructs a new informer for NamespacedValidatingPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNamespacedValidatingPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PoliciesV1beta1().NamespacedValidatingPolicies(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PoliciesV1beta1().NamespacedValidatingPolicies(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PoliciesV1beta1().NamespacedValidatingPolicies(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PoliciesV1beta1().NamespacedValidatingPolicies(namespace).Watch(ctx, options)
			},
		}, client),
		&apipolicieskyvernoiov1beta1.NamespacedValidatingPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *namespacedValidatingPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNamespacedValidatingPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *namespacedValidatingPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apipolicieskyvernoiov1beta1.NamespacedValidatingPolicy{}, f.defaultInformer)
}

func (f *namespacedValidatingPolicyInformer) Lister() policieskyvernoiov1beta1.NamespacedValidatingPolicyLister {
	return policieskyvernoiov1beta1.NewNamespacedValidatingPolicyLister(f.Informer().GetIndexer())
}
