/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/admission/v1"
)

// AdmissionRequestInfoObjectApplyConfiguration represents an declarative configuration of the AdmissionRequestInfoObject type for use
// with apply.
type AdmissionRequestInfoObjectApplyConfiguration struct {
	AdmissionRequest *v1.AdmissionRequest `json:"admissionRequest,omitempty"`
	Operation        *v1.Operation        `json:"operation,omitempty"`
}

// AdmissionRequestInfoObjectApplyConfiguration constructs an declarative configuration of the AdmissionRequestInfoObject type for use with
// apply.
func AdmissionRequestInfoObject() *AdmissionRequestInfoObjectApplyConfiguration {
	return &AdmissionRequestInfoObjectApplyConfiguration{}
}

// WithAdmissionRequest sets the AdmissionRequest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdmissionRequest field is set to the value of the last call.
func (b *AdmissionRequestInfoObjectApplyConfiguration) WithAdmissionRequest(value v1.AdmissionRequest) *AdmissionRequestInfoObjectApplyConfiguration {
	b.AdmissionRequest = &value
	return b
}

// WithOperation sets the Operation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Operation field is set to the value of the last call.
func (b *AdmissionRequestInfoObjectApplyConfiguration) WithOperation(value v1.Operation) *AdmissionRequestInfoObjectApplyConfiguration {
	b.Operation = &value
	return b
}
