apiVersion: "example.com/v1"
kind: Bar
metadata:
  name: test-bar
spec:
  containers:
    - name: foo
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
