/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	policieskyvernoiov1alpha1 "github.com/kyverno/kyverno/api/policies.kyverno.io/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DeletingPolicyLister helps list DeletingPolicies.
// All objects returned here must be treated as read-only.
type DeletingPolicyLister interface {
	// List lists all DeletingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*policieskyvernoiov1alpha1.DeletingPolicy, err error)
	// Get retrieves the DeletingPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*policieskyvernoiov1alpha1.DeletingPolicy, error)
	DeletingPolicyListerExpansion
}

// deletingPolicyLister implements the DeletingPolicyLister interface.
type deletingPolicyLister struct {
	listers.ResourceIndexer[*policieskyvernoiov1alpha1.DeletingPolicy]
}

// NewDeletingPolicyLister returns a new DeletingPolicyLister.
func NewDeletingPolicyLister(indexer cache.Indexer) DeletingPolicyLister {
	return &deletingPolicyLister{listers.New[*policieskyvernoiov1alpha1.DeletingPolicy](indexer, policieskyvernoiov1alpha1.Resource("deletingpolicy"))}
}
