/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	policieskyvernoiov1alpha1 "github.com/kyverno/kyverno/api/policies.kyverno.io/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MutatingPolicyLister helps list MutatingPolicies.
// All objects returned here must be treated as read-only.
type MutatingPolicyLister interface {
	// List lists all MutatingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*policieskyvernoiov1alpha1.MutatingPolicy, err error)
	// Get retrieves the MutatingPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*policieskyvernoiov1alpha1.MutatingPolicy, error)
	MutatingPolicyListerExpansion
}

// mutatingPolicyLister implements the MutatingPolicyLister interface.
type mutatingPolicyLister struct {
	listers.ResourceIndexer[*policieskyvernoiov1alpha1.MutatingPolicy]
}

// NewMutatingPolicyLister returns a new MutatingPolicyLister.
func NewMutatingPolicyLister(indexer cache.Indexer) MutatingPolicyLister {
	return &mutatingPolicyLister{listers.New[*policieskyvernoiov1alpha1.MutatingPolicy](indexer, policieskyvernoiov1alpha1.Resource("mutatingpolicy"))}
}
