/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kyvernov1 "github.com/nirmata/kyverno/pkg/api/kyverno/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterKyvernoPolicyReports implements ClusterKyvernoPolicyReportInterface
type FakeClusterKyvernoPolicyReports struct {
	Fake *FakeKyvernoV1
}

var clusterkyvernopolicyreportsResource = schema.GroupVersionResource{Group: "kyverno.io", Version: "v1", Resource: "clusterkyvernopolicyreports"}

var clusterkyvernopolicyreportsKind = schema.GroupVersionKind{Group: "kyverno.io", Version: "v1", Kind: "ClusterKyvernoPolicyReport"}

// Get takes name of the clusterKyvernoPolicyReport, and returns the corresponding clusterKyvernoPolicyReport object, and an error if there is any.
func (c *FakeClusterKyvernoPolicyReports) Get(name string, options v1.GetOptions) (result *kyvernov1.ClusterKyvernoPolicyReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterkyvernopolicyreportsResource, name), &kyvernov1.ClusterKyvernoPolicyReport{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kyvernov1.ClusterKyvernoPolicyReport), err
}

// List takes label and field selectors, and returns the list of ClusterKyvernoPolicyReports that match those selectors.
func (c *FakeClusterKyvernoPolicyReports) List(opts v1.ListOptions) (result *kyvernov1.ClusterKyvernoPolicyReportList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterkyvernopolicyreportsResource, clusterkyvernopolicyreportsKind, opts), &kyvernov1.ClusterKyvernoPolicyReportList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kyvernov1.ClusterKyvernoPolicyReportList{ListMeta: obj.(*kyvernov1.ClusterKyvernoPolicyReportList).ListMeta}
	for _, item := range obj.(*kyvernov1.ClusterKyvernoPolicyReportList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterKyvernoPolicyReports.
func (c *FakeClusterKyvernoPolicyReports) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterkyvernopolicyreportsResource, opts))
}

// Create takes the representation of a clusterKyvernoPolicyReport and creates it.  Returns the server's representation of the clusterKyvernoPolicyReport, and an error, if there is any.
func (c *FakeClusterKyvernoPolicyReports) Create(clusterKyvernoPolicyReport *kyvernov1.ClusterKyvernoPolicyReport) (result *kyvernov1.ClusterKyvernoPolicyReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterkyvernopolicyreportsResource, clusterKyvernoPolicyReport), &kyvernov1.ClusterKyvernoPolicyReport{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kyvernov1.ClusterKyvernoPolicyReport), err
}

// Update takes the representation of a clusterKyvernoPolicyReport and updates it. Returns the server's representation of the clusterKyvernoPolicyReport, and an error, if there is any.
func (c *FakeClusterKyvernoPolicyReports) Update(clusterKyvernoPolicyReport *kyvernov1.ClusterKyvernoPolicyReport) (result *kyvernov1.ClusterKyvernoPolicyReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterkyvernopolicyreportsResource, clusterKyvernoPolicyReport), &kyvernov1.ClusterKyvernoPolicyReport{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kyvernov1.ClusterKyvernoPolicyReport), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterKyvernoPolicyReports) UpdateStatus(clusterKyvernoPolicyReport *kyvernov1.ClusterKyvernoPolicyReport) (*kyvernov1.ClusterKyvernoPolicyReport, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterkyvernopolicyreportsResource, "status", clusterKyvernoPolicyReport), &kyvernov1.ClusterKyvernoPolicyReport{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kyvernov1.ClusterKyvernoPolicyReport), err
}

// Delete takes name of the clusterKyvernoPolicyReport and deletes it. Returns an error if one occurs.
func (c *FakeClusterKyvernoPolicyReports) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clusterkyvernopolicyreportsResource, name), &kyvernov1.ClusterKyvernoPolicyReport{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterKyvernoPolicyReports) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterkyvernopolicyreportsResource, listOptions)

	_, err := c.Fake.Invokes(action, &kyvernov1.ClusterKyvernoPolicyReportList{})
	return err
}

// Patch applies the patch and returns the patched clusterKyvernoPolicyReport.
func (c *FakeClusterKyvernoPolicyReports) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *kyvernov1.ClusterKyvernoPolicyReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterkyvernopolicyreportsResource, name, pt, data, subresources...), &kyvernov1.ClusterKyvernoPolicyReport{})
	if obj == nil {
		return nil, err
	}
	return obj.(*kyvernov1.ClusterKyvernoPolicyReport), err
}
