/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	kyvernov1 "github.com/nirmata/kyverno/pkg/api/kyverno/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKyvernoPolicyReports implements KyvernoPolicyReportInterface
type FakeKyvernoPolicyReports struct {
	Fake *FakeKyvernoV1
	ns   string
}

var kyvernopolicyreportsResource = schema.GroupVersionResource{Group: "kyverno.io", Version: "v1", Resource: "kyvernopolicyreports"}

var kyvernopolicyreportsKind = schema.GroupVersionKind{Group: "kyverno.io", Version: "v1", Kind: "KyvernoPolicyReport"}

// Get takes name of the kyvernoPolicyReport, and returns the corresponding kyvernoPolicyReport object, and an error if there is any.
func (c *FakeKyvernoPolicyReports) Get(ctx context.Context, name string, options v1.GetOptions) (result *kyvernov1.KyvernoPolicyReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kyvernopolicyreportsResource, c.ns, name), &kyvernov1.KyvernoPolicyReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kyvernov1.KyvernoPolicyReport), err
}

// List takes label and field selectors, and returns the list of KyvernoPolicyReports that match those selectors.
func (c *FakeKyvernoPolicyReports) List(ctx context.Context, opts v1.ListOptions) (result *kyvernov1.KyvernoPolicyReportList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kyvernopolicyreportsResource, kyvernopolicyreportsKind, c.ns, opts), &kyvernov1.KyvernoPolicyReportList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kyvernov1.KyvernoPolicyReportList{ListMeta: obj.(*kyvernov1.KyvernoPolicyReportList).ListMeta}
	for _, item := range obj.(*kyvernov1.KyvernoPolicyReportList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kyvernoPolicyReports.
func (c *FakeKyvernoPolicyReports) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kyvernopolicyreportsResource, c.ns, opts))

}

// Create takes the representation of a kyvernoPolicyReport and creates it.  Returns the server's representation of the kyvernoPolicyReport, and an error, if there is any.
func (c *FakeKyvernoPolicyReports) Create(ctx context.Context, kyvernoPolicyReport *kyvernov1.KyvernoPolicyReport, opts v1.CreateOptions) (result *kyvernov1.KyvernoPolicyReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kyvernopolicyreportsResource, c.ns, kyvernoPolicyReport), &kyvernov1.KyvernoPolicyReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kyvernov1.KyvernoPolicyReport), err
}

// Update takes the representation of a kyvernoPolicyReport and updates it. Returns the server's representation of the kyvernoPolicyReport, and an error, if there is any.
func (c *FakeKyvernoPolicyReports) Update(ctx context.Context, kyvernoPolicyReport *kyvernov1.KyvernoPolicyReport, opts v1.UpdateOptions) (result *kyvernov1.KyvernoPolicyReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kyvernopolicyreportsResource, c.ns, kyvernoPolicyReport), &kyvernov1.KyvernoPolicyReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kyvernov1.KyvernoPolicyReport), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKyvernoPolicyReports) UpdateStatus(ctx context.Context, kyvernoPolicyReport *kyvernov1.KyvernoPolicyReport, opts v1.UpdateOptions) (*kyvernov1.KyvernoPolicyReport, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kyvernopolicyreportsResource, "status", c.ns, kyvernoPolicyReport), &kyvernov1.KyvernoPolicyReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kyvernov1.KyvernoPolicyReport), err
}

// Delete takes name of the kyvernoPolicyReport and deletes it. Returns an error if one occurs.
func (c *FakeKyvernoPolicyReports) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kyvernopolicyreportsResource, c.ns, name), &kyvernov1.KyvernoPolicyReport{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKyvernoPolicyReports) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kyvernopolicyreportsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &kyvernov1.KyvernoPolicyReportList{})
	return err
}

// Patch applies the patch and returns the patched kyvernoPolicyReport.
func (c *FakeKyvernoPolicyReports) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kyvernov1.KyvernoPolicyReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kyvernopolicyreportsResource, c.ns, name, pt, data, subresources...), &kyvernov1.KyvernoPolicyReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kyvernov1.KyvernoPolicyReport), err
}
