// Command change-scope classifies a set of changed files into structured
// change-scope metadata, so tooling can decide what a diff requires without
// re-deriving it from heuristics.
//
// It answers three questions about a change set:
//
//   - What kind of change is this (docs-only, generated-code-only,
//     API, test-only, …)?
//   - Which verification steps does it require (e.g. a diff touching
//     generated code needs `make verify-codegen`, not a hunt for unit
//     tests that will never exist)?
//   - May automation act on it autonomously, or does it touch a path that
//     always requires human review?
//
// Usage:
//
//	git diff --name-only origin/main... | change-scope
//	change-scope -files pkg/engine/engine.go,docs/README.md
package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

// Category is the classification assigned to a single changed path.
type Category string

const (
	// CategoryGenerated is code produced by a generator. A diff here is
	// verified by re-running codegen, not by unit tests.
	CategoryGenerated Category = "generated"
	// CategoryAPI is hand-written API type definitions. Changes here can
	// be API-breaking and may require regenerating deepcopy/CRDs.
	CategoryAPI Category = "api"
	// CategorySecuritySensitive is signature/attestation verification and
	// TLS material.
	CategorySecuritySensitive Category = "security-sensitive"
	// CategoryTest is unit tests and the conformance suite.
	CategoryTest Category = "test"
	// CategoryDocs is documentation and markdown.
	CategoryDocs Category = "docs"
	// CategoryChart is the Helm charts.
	CategoryChart Category = "chart"
	// CategoryCI is CI workflows and actions.
	CategoryCI Category = "ci"
	// CategoryBuild is the build system and dependency manifests.
	CategoryBuild Category = "build"
	// CategorySource is ordinary hand-written Go outside the above.
	CategorySource Category = "source"
)

// Classification is the result for a single path.
type Classification struct {
	Path     string   `json:"path"`
	Category Category `json:"category"`
	// AutonomousOK reports whether automation may modify this path
	// without human review.
	AutonomousOK bool `json:"autonomousOk"`
	// Reason explains the classification, so a reviewer can tell why a
	// path was treated the way it was.
	Reason string `json:"reason"`
}

// Result aggregates the per-path classifications into the summary a caller
// acts on.
type Result struct {
	Files []Classification `json:"files"`
	// Categories is the deduplicated, sorted set of categories present.
	Categories []Category `json:"categories"`
	// Scope is a single label for the whole change set: "<category>-only"
	// when every path shares a category, otherwise "mixed".
	Scope string `json:"scope"`
	// AutonomousOK is true only when every path permits autonomous action.
	AutonomousOK bool `json:"autonomousOk"`
	// RequiredChecks are the make targets this change set should be
	// verified with, deduplicated and sorted.
	RequiredChecks []string `json:"requiredChecks"`
}

// rule maps a path prefix or suffix to a classification. Rules are
// evaluated in order and the first match wins, so more specific rules must
// come first.
type rule struct {
	// match reports whether the rule applies to path.
	match func(path string) bool
	// category assigned on match.
	category Category
	// autonomousOK reports whether automation may touch this path unattended.
	autonomousOK bool
	// reason is a short human-readable justification.
	reason string
	// checks are make targets required to verify a change to this path.
	checks []string
}

func hasPrefix(prefixes ...string) func(string) bool {
	return func(path string) bool {
		for _, p := range prefixes {
			if strings.HasPrefix(path, p) {
				return true
			}
		}
		return false
	}
}

func hasSuffix(suffixes ...string) func(string) bool {
	return func(path string) bool {
		for _, s := range suffixes {
			if strings.HasSuffix(path, s) {
				return true
			}
		}
		return false
	}
}

func isExactly(names ...string) func(string) bool {
	return func(path string) bool {
		for _, n := range names {
			if path == n {
				return true
			}
		}
		return false
	}
}

func anyOf(fns ...func(string) bool) func(string) bool {
	return func(path string) bool {
		for _, fn := range fns {
			if fn(path) {
				return true
			}
		}
		return false
	}
}

// rules is the ordered rule set. Order matters: generated code lives under
// api/ and pkg/, so those rules precede the broader api/ and source rules.
var rules = []rule{
	{
		// pkg/clients is generated by `make codegen-client-wrappers` (via
		// hack/client-wrapper) but, unlike pkg/client, its files carry no
		// "Code generated ... DO NOT EDIT" marker. Detecting generated code
		// by that marker alone therefore misses it, which is why generated
		// paths are enumerated here rather than sniffed.
		match:        anyOf(hasPrefix("pkg/client/", "pkg/clients/", "config/crds/"), hasSuffix("zz_generated.deepcopy.go")),
		category:     CategoryGenerated,
		autonomousOK: false,
		reason:       "generated output; verify by re-running codegen rather than editing directly",
		checks:       []string{"verify-codegen"},
	},
	{
		match:        hasPrefix("api/"),
		category:     CategoryAPI,
		autonomousOK: false,
		reason:       "API type definitions; changes may be breaking and require regeneration",
		checks:       []string{"verify-codegen", "test-unit"},
	},
	{
		// The paths named in the original proposal (pkg/cosign, pkg/notary)
		// no longer exist; verification now lives under pkg/image/verifiers
		// and pkg/sigstoretuf.
		match:        hasPrefix("pkg/image/verifiers/", "pkg/sigstoretuf/", "pkg/tls/"),
		category:     CategorySecuritySensitive,
		autonomousOK: false,
		reason:       "signature/attestation verification or TLS material; always requires human review",
		checks:       []string{"test-unit"},
	},
	{
		match:        anyOf(hasSuffix("_test.go"), hasPrefix("test/")),
		category:     CategoryTest,
		autonomousOK: true,
		reason:       "test-only change",
		checks:       []string{"test-unit"},
	},
	{
		match:        anyOf(hasPrefix("docs/"), hasSuffix(".md")),
		category:     CategoryDocs,
		autonomousOK: true,
		reason:       "documentation only",
		checks:       nil,
	},
	{
		match:        hasPrefix("charts/"),
		category:     CategoryChart,
		autonomousOK: false,
		reason:       "Helm chart; affects released artifacts",
		checks:       []string{"verify-helm-docs"},
	},
	{
		match:        hasPrefix(".github/"),
		category:     CategoryCI,
		autonomousOK: false,
		reason:       "CI configuration; can alter what checks run on every change",
		checks:       nil,
	},
	{
		match:        anyOf(isExactly("Makefile", "go.mod", "go.sum"), hasSuffix(".mk")),
		category:     CategoryBuild,
		autonomousOK: false,
		reason:       "build system or dependency manifest",
		checks:       []string{"build-all", "test-unit"},
	},
	{
		match:        func(string) bool { return true },
		category:     CategorySource,
		autonomousOK: false,
		reason:       "hand-written source",
		checks:       []string{"test-unit", "lint"},
	},
}

// Classify assigns a classification to a single path.
func Classify(path string) Classification {
	for _, r := range rules {
		if r.match(path) {
			return Classification{
				Path:         path,
				Category:     r.category,
				AutonomousOK: r.autonomousOK,
				Reason:       r.reason,
			}
		}
	}
	// Unreachable: the final rule matches everything.
	return Classification{Path: path, Category: CategorySource}
}

// Analyze classifies every path and aggregates the results.
func Analyze(paths []string) Result {
	result := Result{
		Files:        []Classification{},
		Categories:   []Category{},
		AutonomousOK: len(paths) > 0,
	}

	seenCategory := map[Category]bool{}
	seenCheck := map[string]bool{}

	for _, path := range paths {
		c := Classify(path)
		result.Files = append(result.Files, c)

		if !c.AutonomousOK {
			result.AutonomousOK = false
		}
		if !seenCategory[c.Category] {
			seenCategory[c.Category] = true
			result.Categories = append(result.Categories, c.Category)
		}
		for _, r := range rules {
			if r.category == c.Category {
				for _, check := range r.checks {
					seenCheck[check] = true
				}
				break
			}
		}
	}

	sort.Slice(result.Categories, func(i, j int) bool {
		return result.Categories[i] < result.Categories[j]
	})

	result.RequiredChecks = make([]string, 0, len(seenCheck))
	for check := range seenCheck {
		result.RequiredChecks = append(result.RequiredChecks, check)
	}
	sort.Strings(result.RequiredChecks)

	switch len(result.Categories) {
	case 0:
		result.Scope = "empty"
	case 1:
		result.Scope = string(result.Categories[0]) + "-only"
	default:
		result.Scope = "mixed"
	}

	return result
}

func main() {
	files := flag.String("files", "", "comma-separated paths; if unset, paths are read from stdin one per line")
	out := flag.String("out", "", "output file path (defaults to stdout)")
	flag.Parse()

	paths, err := readPaths(*files)
	if err != nil {
		fmt.Fprintln(os.Stderr, "change-scope:", err)
		os.Exit(1)
	}

	w := os.Stdout
	if *out != "" {
		f, err := os.Create(*out)
		if err != nil {
			fmt.Fprintln(os.Stderr, "change-scope:", err)
			os.Exit(1)
		}
		defer f.Close()
		w = f
	}

	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	if err := enc.Encode(Analyze(paths)); err != nil {
		fmt.Fprintln(os.Stderr, "change-scope:", err)
		os.Exit(1)
	}
}

// readPaths collects paths from the -files flag when set, otherwise from
// stdin. Blank lines are ignored so `git diff --name-only` output can be
// piped in directly.
func readPaths(files string) ([]string, error) {
	var paths []string
	if files != "" {
		for _, p := range strings.Split(files, ",") {
			if p = strings.TrimSpace(p); p != "" {
				paths = append(paths, p)
			}
		}
		return paths, nil
	}
	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		if p := strings.TrimSpace(scanner.Text()); p != "" {
			paths = append(paths, p)
		}
	}
	return paths, scanner.Err()
}
