/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	policieskyvernoiov1 "github.com/kyverno/kyverno/api/policies.kyverno.io/v1"
	scheme "github.com/kyverno/kyverno/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NamespacedGeneratingPoliciesGetter has a method to return a NamespacedGeneratingPolicyInterface.
// A group's client should implement this interface.
type NamespacedGeneratingPoliciesGetter interface {
	NamespacedGeneratingPolicies(namespace string) NamespacedGeneratingPolicyInterface
}

// NamespacedGeneratingPolicyInterface has methods to work with NamespacedGeneratingPolicy resources.
type NamespacedGeneratingPolicyInterface interface {
	Create(ctx context.Context, namespacedGeneratingPolicy *policieskyvernoiov1.NamespacedGeneratingPolicy, opts metav1.CreateOptions) (*policieskyvernoiov1.NamespacedGeneratingPolicy, error)
	Update(ctx context.Context, namespacedGeneratingPolicy *policieskyvernoiov1.NamespacedGeneratingPolicy, opts metav1.UpdateOptions) (*policieskyvernoiov1.NamespacedGeneratingPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, namespacedGeneratingPolicy *policieskyvernoiov1.NamespacedGeneratingPolicy, opts metav1.UpdateOptions) (*policieskyvernoiov1.NamespacedGeneratingPolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*policieskyvernoiov1.NamespacedGeneratingPolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*policieskyvernoiov1.NamespacedGeneratingPolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *policieskyvernoiov1.NamespacedGeneratingPolicy, err error)
	NamespacedGeneratingPolicyExpansion
}

// namespacedGeneratingPolicies implements NamespacedGeneratingPolicyInterface
type namespacedGeneratingPolicies struct {
	*gentype.ClientWithList[*policieskyvernoiov1.NamespacedGeneratingPolicy, *policieskyvernoiov1.NamespacedGeneratingPolicyList]
}

// newNamespacedGeneratingPolicies returns a NamespacedGeneratingPolicies
func newNamespacedGeneratingPolicies(c *PoliciesV1Client, namespace string) *namespacedGeneratingPolicies {
	return &namespacedGeneratingPolicies{
		gentype.NewClientWithList[*policieskyvernoiov1.NamespacedGeneratingPolicy, *policieskyvernoiov1.NamespacedGeneratingPolicyList](
			"namespacedgeneratingpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *policieskyvernoiov1.NamespacedGeneratingPolicy {
				return &policieskyvernoiov1.NamespacedGeneratingPolicy{}
			},
			func() *policieskyvernoiov1.NamespacedGeneratingPolicyList {
				return &policieskyvernoiov1.NamespacedGeneratingPolicyList{}
			},
		),
	}
}
