package engine

import (
	"context"
	"slices"
	"testing"

	policieskyvernoio "github.com/kyverno/api/api/policies.kyverno.io"
	policiesv1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	"github.com/kyverno/kyverno/pkg/cel/policies/vpol/compiler"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TestNewProvider_AutogenExceptionRewrite is a regression test for #16952:
// a PolicyException's matchConditions must be rewritten the same way the
// policy's own expressions are for each autogen'd controller variant.
func TestNewProvider_AutogenExceptionRewrite(t *testing.T) {
	policy := &policiesv1beta1.ValidatingPolicy{
		ObjectMeta: metav1.ObjectMeta{Name: "disallow-privilege-escalation"},
		Spec: policiesv1beta1.ValidatingPolicySpec{
			EvaluationConfiguration: &policiesv1beta1.EvaluationConfiguration{
				Mode: policieskyvernoio.EvaluationModeJSON,
			},
			AutogenConfiguration: &policiesv1beta1.ValidatingPolicyAutogenConfiguration{
				PodControllers: &policiesv1beta1.PodControllersGenerationConfiguration{
					Controllers: []string{"daemonsets"},
				},
			},
			MatchConstraints: &admissionregistrationv1.MatchResources{
				ResourceRules: []admissionregistrationv1.NamedRuleWithOperations{
					{
						RuleWithOperations: admissionregistrationv1.RuleWithOperations{
							Operations: []admissionregistrationv1.OperationType{admissionregistrationv1.Create, admissionregistrationv1.Update},
							Rule: admissionregistrationv1.Rule{
								APIGroups:   []string{""},
								APIVersions: []string{"v1"},
								Resources:   []string{"pods"},
							},
						},
					},
				},
			},
			Validations: []admissionregistrationv1.Validation{
				{Expression: "object.spec.containers.all(c, !has(c.securityContext) || !has(c.securityContext.allowPrivilegeEscalation) || c.securityContext.allowPrivilegeEscalation == false)"},
			},
		},
	}

	exception := &policiesv1beta1.PolicyException{
		ObjectMeta: metav1.ObjectMeta{Name: "exclude-privileged"},
		Spec: policiesv1beta1.PolicyExceptionSpec{
			PolicyRefs: []policiesv1beta1.PolicyRef{
				{Name: "disallow-privilege-escalation", Kind: "ValidatingPolicy"},
			},
			MatchConditions: []admissionregistrationv1.MatchCondition{
				{
					Name:       "privileged",
					Expression: "object.spec.containers.exists(c, has(c.securityContext) && has(c.securityContext.allowPrivilegeEscalation) && c.securityContext.allowPrivilegeEscalation == true)",
				},
			},
		},
	}

	provider, err := NewProvider(compiler.NewCompiler(), []policiesv1beta1.ValidatingPolicyLike{policy}, []*policiesv1beta1.PolicyException{exception})
	require.NoError(t, err)

	policies, err := provider(context.Background())
	require.NoError(t, err)

	var daemonsetPolicy *Policy
	for i := range policies {
		spec := policies[i].Policy.GetValidatingPolicySpec()
		if spec.MatchConstraints != nil && len(spec.MatchConstraints.ResourceRules) > 0 &&
			slices.Contains(spec.MatchConstraints.ResourceRules[0].Resources, "daemonsets") {
			daemonsetPolicy = &policies[i]
			break
		}
	}
	require.NotNil(t, daemonsetPolicy, "expected an autogenerated daemonsets policy variant")

	// A DaemonSet whose pod template container allows privilege escalation.
	// Without the fix, the exception's matchCondition still reads
	// object.spec.containers (Pod-shaped) and errors with "no such key:
	// containers" against this DaemonSet-shaped object.
	daemonset := map[string]any{
		"spec": map[string]any{
			"template": map[string]any{
				"spec": map[string]any{
					"containers": []any{
						map[string]any{
							"name": "agent",
							"securityContext": map[string]any{
								"allowPrivilegeEscalation": true,
							},
						},
					},
				},
			},
		},
	}

	result, err := daemonsetPolicy.CompiledPolicy.Evaluate(context.Background(), daemonset, nil, nil, nil, nil)
	require.NoError(t, err)
	require.NotNil(t, result)
	assert.NotEmpty(t, result.Exceptions, "the privileged daemonset should be excepted, not evaluated against validations")
}
