/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	policieskyvernoiov1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	scheme "github.com/kyverno/kyverno/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NamespacedMutatingPoliciesGetter has a method to return a NamespacedMutatingPolicyInterface.
// A group's client should implement this interface.
type NamespacedMutatingPoliciesGetter interface {
	NamespacedMutatingPolicies(namespace string) NamespacedMutatingPolicyInterface
}

// NamespacedMutatingPolicyInterface has methods to work with NamespacedMutatingPolicy resources.
type NamespacedMutatingPolicyInterface interface {
	Create(ctx context.Context, namespacedMutatingPolicy *policieskyvernoiov1beta1.NamespacedMutatingPolicy, opts v1.CreateOptions) (*policieskyvernoiov1beta1.NamespacedMutatingPolicy, error)
	Update(ctx context.Context, namespacedMutatingPolicy *policieskyvernoiov1beta1.NamespacedMutatingPolicy, opts v1.UpdateOptions) (*policieskyvernoiov1beta1.NamespacedMutatingPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, namespacedMutatingPolicy *policieskyvernoiov1beta1.NamespacedMutatingPolicy, opts v1.UpdateOptions) (*policieskyvernoiov1beta1.NamespacedMutatingPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*policieskyvernoiov1beta1.NamespacedMutatingPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*policieskyvernoiov1beta1.NamespacedMutatingPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *policieskyvernoiov1beta1.NamespacedMutatingPolicy, err error)
	NamespacedMutatingPolicyExpansion
}

// namespacedMutatingPolicies implements NamespacedMutatingPolicyInterface
type namespacedMutatingPolicies struct {
	*gentype.ClientWithList[*policieskyvernoiov1beta1.NamespacedMutatingPolicy, *policieskyvernoiov1beta1.NamespacedMutatingPolicyList]
}

// newNamespacedMutatingPolicies returns a NamespacedMutatingPolicies
func newNamespacedMutatingPolicies(c *PoliciesV1beta1Client, namespace string) *namespacedMutatingPolicies {
	return &namespacedMutatingPolicies{
		gentype.NewClientWithList[*policieskyvernoiov1beta1.NamespacedMutatingPolicy, *policieskyvernoiov1beta1.NamespacedMutatingPolicyList](
			"namespacedmutatingpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *policieskyvernoiov1beta1.NamespacedMutatingPolicy {
				return &policieskyvernoiov1beta1.NamespacedMutatingPolicy{}
			},
			func() *policieskyvernoiov1beta1.NamespacedMutatingPolicyList {
				return &policieskyvernoiov1beta1.NamespacedMutatingPolicyList{}
			},
		),
	}
}
