package engine

import (
	"context"
	"encoding/json"
	"testing"

	kyvernov1 "github.com/kyverno/kyverno/api/kyverno/v1"
	"github.com/kyverno/kyverno/pkg/registryclient"
	webhookutils "github.com/kyverno/kyverno/pkg/utils/engine"
	kubeutils "github.com/kyverno/kyverno/pkg/utils/kube"
	"gotest.tools/assert"
)

// A single ClusterPolicy with two validate rules that have different per-rule failureAction
// (one Audit, one Enforce). Each rule's own failureAction must be honored: a resource that
// fails the Enforce rule must be blocked regardless of rule order, and a resource that fails
// only the Audit rule must not be blocked even though an Enforce rule is present.
//
// webhookutils.BlockRequest (pkg/utils/engine) is exactly the admission block decision:
// pkg/webhooks/utils.BlockRequest loops the responses and calls it.

const auditTeamRule = `{
	"name": "require-team-label",
	"match": {"any": [{"resources": {"kinds": ["Pod"]}}]},
	"validate": {"failureAction": "Audit", "message": "team label is required",
		"pattern": {"metadata": {"labels": {"team": "?*"}}}}
}`

const enforceOwnerRule = `{
	"name": "require-owner-label",
	"match": {"any": [{"resources": {"kinds": ["Pod"]}}]},
	"validate": {"failureAction": "Enforce", "message": "owner label is required",
		"pattern": {"metadata": {"labels": {"owner": "?*"}}}}
}`

func pod(labels string) []byte {
	return []byte(`{"apiVersion": "v1", "kind": "Pod",
		"metadata": {"name": "app", "namespace": "default", "labels": {` + labels + `}},
		"spec": {"containers": [{"name": "app", "image": "nginx"}]}}`)
}

func runMixed(t *testing.T, rulesJSON string, podJSON []byte) bool {
	t.Helper()
	rawPolicy := []byte(`{"apiVersion": "kyverno.io/v1", "kind": "ClusterPolicy",
		"metadata": {"name": "team-and-owner"}, "spec": {"rules": [` + rulesJSON + `]}}`)
	var policy kyvernov1.ClusterPolicy
	assert.NilError(t, json.Unmarshal(rawPolicy, &policy))
	resource, err := kubeutils.BytesToUnstructured(podJSON)
	assert.NilError(t, err)
	pc := newPolicyContext(t, *resource, kyvernov1.Create, nil).WithPolicy(&policy)
	er := testValidate(context.TODO(), registryclient.NewOrDie(), pc, cfg, nil)
	return webhookutils.BlockRequest(er, kyvernov1.Fail)
}

// deployment builds a Deployment whose pod template carries the given labels. Autogen rewrites
// the pod label rules to target spec.template.metadata.labels and renames them (autogen-<rule>),
// so this exercises the per-rule action resolution against the autogenerated rule set.
func deployment(labels string) []byte {
	return []byte(`{"apiVersion": "apps/v1", "kind": "Deployment",
		"metadata": {"name": "app", "namespace": "default"},
		"spec": {"selector": {"matchLabels": {"app": "x"}},
			"template": {"metadata": {"labels": {` + labels + `}},
				"spec": {"containers": [{"name": "app", "image": "nginx"}]}}}}`)
}

func TestMixedFailureAction_BlockIsPerRule_Autogen(t *testing.T) {
	// Pod template has team, no owner -> fails the autogen Enforce (owner) rule. Must block
	// in both orderings even though the response rules are named autogen-<rule>.
	teamNoOwner := deployment(`"team": "payments"`)
	assert.Equal(t, true, runMixed(t, auditTeamRule+","+enforceOwnerRule, teamNoOwner),
		"autogen: enforce rule fails, must block with audit rule first")
	assert.Equal(t, true, runMixed(t, enforceOwnerRule+","+auditTeamRule, teamNoOwner),
		"autogen: enforce rule fails, must block with enforce rule first")

	// Pod template has owner, no team -> only the autogen Audit rule fails. Must not block.
	ownerNoTeam := deployment(`"owner": "alice"`)
	assert.Equal(t, false, runMixed(t, auditTeamRule+","+enforceOwnerRule, ownerNoTeam),
		"autogen: only the audit rule fails, request must be admitted")
}

func TestMixedFailureAction_BlockIsPerRule(t *testing.T) {
	// Pod has team, no owner -> fails the Enforce (owner) rule. Must block in BOTH orderings.
	teamNoOwner := pod(`"team": "payments"`)
	assert.Equal(t, true, runMixed(t, auditTeamRule+","+enforceOwnerRule, teamNoOwner),
		"enforce rule fails: must block even when an audit rule is listed first (was fail-open)")
	assert.Equal(t, true, runMixed(t, enforceOwnerRule+","+auditTeamRule, teamNoOwner),
		"enforce rule fails: must block when listed first")

	// Pod has owner, no team -> fails the Audit (team) rule only; Enforce rule passes.
	// Must NOT block just because an Enforce rule exists (guards against over-blocking).
	ownerNoTeam := pod(`"owner": "alice"`)
	assert.Equal(t, false, runMixed(t, auditTeamRule+","+enforceOwnerRule, ownerNoTeam),
		"only the audit rule fails: request must be admitted")
	assert.Equal(t, false, runMixed(t, enforceOwnerRule+","+auditTeamRule, ownerNoTeam),
		"only the audit rule fails: request must be admitted (enforce rule first)")
}
