package engine

import (
	"context"
	"fmt"

	policieskyvernoio "github.com/kyverno/api/api/policies.kyverno.io"
	policiesv1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	"github.com/kyverno/kyverno/pkg/cel/autogen"
	"github.com/kyverno/kyverno/pkg/cel/engine"
	ivpolautogen "github.com/kyverno/kyverno/pkg/cel/policies/ivpol/autogen"
	eval "github.com/kyverno/kyverno/pkg/image/verification/evaluator"
	"github.com/kyverno/kyverno/pkg/logging"
	"k8s.io/apimachinery/pkg/util/sets"
	"k8s.io/client-go/util/workqueue"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

type Provider = engine.Provider[Policy]

type ProviderFunc func(context.Context) ([]Policy, error)

func (f ProviderFunc) Fetch(ctx context.Context) ([]Policy, error) {
	return f(ctx)
}

func NewProvider(compiler eval.Compiler, policies []policiesv1beta1.ImageValidatingPolicyLike, exceptions []*policiesv1beta1.PolicyException) (ProviderFunc, error) {
	compiled := make([]Policy, 0, len(policies))
	for _, policy := range policies {
		p := policy
		var matchedExceptions []*policiesv1beta1.PolicyException
		for _, polex := range exceptions {
			for _, ref := range polex.Spec.PolicyRefs {
				if ref.Name == p.GetName() && ref.Kind == p.GetKind() {
					matchedExceptions = append(matchedExceptions, polex)
				}
			}
		}
		program, errs := compiler.Compile(p, matchedExceptions)
		if len(errs) != 0 {
			return nil, errs.ToAggregate()
		}
		actions := sets.New(p.GetSpec().ValidationActions()...)
		compiled = append(compiled, Policy{
			CompiledPolicy: program,
			Actions:        actions,
			Policy:         p,
			Exceptions:     matchedExceptions,
		})
		autogeneratedIvPols, err := ivpolautogen.Autogen(p)
		if err != nil {
			return nil, err
		}
		for config, ap := range autogeneratedIvPols {
			autogenPolicy := p.DeepCopyObject().(policiesv1beta1.ImageValidatingPolicyLike)
			*autogenPolicy.GetSpec() = *ap.Spec
			program, errs := compiler.Compile(autogenPolicy, matchedExceptions)
			if len(errs) != 0 {
				return nil, errs.ToAggregate()
			}
			compiled = append(compiled, Policy{
				CompiledPolicy: program,
				Actions:        actions,
				Policy:         autogenPolicy,
				Exceptions:     matchedExceptions,
				ExtractionMode: config == ivpolautogen.ExtractionReplacementsRef,
			})
		}
	}
	provider := func(context.Context) ([]Policy, error) {
		return compiled, nil
	}
	return provider, nil
}

func NewKubeProvider(
	compiler eval.Compiler,
	mgr ctrl.Manager,
	polexLister engine.PolicyExceptionLister,
	polexEnabled bool,
) (Provider, error) {
	// Lets an unrecognized bare controller name (e.g. "jobsets") resolve via
	// live discovery instead of requiring the explicit
	// "<resource>.<version>.<group>" format - see autogen.BareNameResolver.
	// Also corrects the explicit format's best-effort Kind guess (see
	// autogen.KindResolver) for irregular plurals like "jobsets" -> "JobSet".
	autogen.BareNameResolver = autogen.RESTMapperBareNameResolver(mgr.GetRESTMapper())
	autogen.KindResolver = autogen.RESTMapperKindResolver(mgr.GetRESTMapper())
	reconciler := newReconciler(compiler, mgr.GetClient(), polexLister, polexEnabled)
	ivpolBuilder := ctrl.NewControllerManagedBy(mgr).
		For(&policiesv1beta1.ImageValidatingPolicy{})

	nivpolBuilder := ctrl.NewControllerManagedBy(mgr).
		For(&policiesv1beta1.NamespacedImageValidatingPolicy{})

	if polexEnabled {
		exceptionHandlerFuncs := newPolicyExceptionHandler(mgr.GetClient())
		ivpolBuilder = ivpolBuilder.Watches(&policiesv1beta1.PolicyException{}, exceptionHandlerFuncs)
		nivpolBuilder = nivpolBuilder.Watches(&policiesv1beta1.PolicyException{}, exceptionHandlerFuncs)
	}

	if err := ivpolBuilder.Complete(reconciler); err != nil {
		return nil, fmt.Errorf("failed to construct imagevalidatingpolicy manager: %w", err)
	}
	if err := nivpolBuilder.Complete(reconciler); err != nil {
		return nil, fmt.Errorf("failed to construct namespacedimagevalidatingpolicy manager: %w", err)
	}
	return reconciler, nil
}

type policyExceptionQueue = workqueue.TypedRateLimitingInterface[reconcile.Request]

// newPolicyExceptionHandler requeues the policies a PolicyException refers to.
// Policy refs carry no namespace, so a ref to a namespaced policy requeues every
// NamespacedImageValidatingPolicy with that name.
func newPolicyExceptionHandler(c client.Client) *handler.Funcs {
	enqueue := func(ctx context.Context, obj client.Object, q policyExceptionQueue) {
		polex, ok := obj.(*policiesv1beta1.PolicyException)
		if !ok {
			return
		}
		for _, ref := range polex.Spec.PolicyRefs {
			switch ref.Kind {
			case policieskyvernoio.ImageValidatingPolicyKind:
				q.Add(reconcile.Request{NamespacedName: client.ObjectKey{Name: ref.Name}})
			case policieskyvernoio.NamespacedImageValidatingPolicyKind:
				var policies policiesv1beta1.NamespacedImageValidatingPolicyList
				if err := c.List(ctx, &policies); err != nil {
					logging.Error(err, "failed to list namespaced image validating policies", "policy", ref.Name)
					continue
				}
				for _, policy := range policies.Items {
					if policy.Name == ref.Name {
						q.Add(reconcile.Request{NamespacedName: client.ObjectKey{Namespace: policy.Namespace, Name: policy.Name}})
					}
				}
			}
		}
	}
	return &handler.Funcs{
		CreateFunc: func(ctx context.Context, e event.TypedCreateEvent[client.Object], q policyExceptionQueue) {
			enqueue(ctx, e.Object, q)
		},
		UpdateFunc: func(ctx context.Context, e event.TypedUpdateEvent[client.Object], q policyExceptionQueue) {
			enqueue(ctx, e.ObjectNew, q)
			enqueue(ctx, e.ObjectOld, q)
		},
		DeleteFunc: func(ctx context.Context, e event.TypedDeleteEvent[client.Object], q policyExceptionQueue) {
			enqueue(ctx, e.Object, q)
		},
	}
}
