package engine

import (
	"context"
	"sync"

	policiesv1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	"github.com/kyverno/kyverno/pkg/cel/engine"
	ivpolautogen "github.com/kyverno/kyverno/pkg/cel/policies/ivpol/autogen"
	eval "github.com/kyverno/kyverno/pkg/image/verification/evaluator"
	"github.com/kyverno/kyverno/pkg/logging"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/util/sets"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type reconciler struct {
	compiler     eval.Compiler
	client       client.Client
	lock         *sync.RWMutex
	policies     map[string][]Policy
	polexLister  engine.PolicyExceptionLister
	polexEnabled bool
}

func newReconciler(
	compiler eval.Compiler,
	client client.Client,
	polexLister engine.PolicyExceptionLister,
	polexEnabled bool,
) *reconciler {
	return &reconciler{
		compiler:     compiler,
		client:       client,
		lock:         &sync.RWMutex{},
		policies:     map[string][]Policy{},
		polexLister:  polexLister,
		polexEnabled: polexEnabled,
	}
}

func (r *reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	var policy policiesv1beta1.ImageValidatingPolicyLike
	if req.NamespacedName.Namespace == "" {
		var ivp policiesv1beta1.ImageValidatingPolicy
		err := r.client.Get(ctx, req.NamespacedName, &ivp)
		if err != nil {
			if errors.IsNotFound(err) {
				r.lock.Lock()
				defer r.lock.Unlock()
				delete(r.policies, req.NamespacedName.String())
				return ctrl.Result{}, nil
			}
			return ctrl.Result{}, err
		}
		policy = &ivp
	} else {
		var nivp policiesv1beta1.NamespacedImageValidatingPolicy
		err := r.client.Get(ctx, req.NamespacedName, &nivp)
		if err != nil {
			if errors.IsNotFound(err) {
				r.lock.Lock()
				defer r.lock.Unlock()
				delete(r.policies, req.NamespacedName.String())
				return ctrl.Result{}, nil
			}
			return ctrl.Result{}, err
		}
		policy = &nivp
	}
	var exceptions []*policiesv1beta1.PolicyException
	var err error
	if r.polexEnabled {
		exceptions, err = engine.ListExceptions(r.polexLister, policy.GetKind(), policy.GetName())
		if err != nil {
			return ctrl.Result{}, err
		}
	}
	autogeneratedIvPols, err := ivpolautogen.Autogen(policy)
	if err != nil {
		return ctrl.Result{}, err
	}
	compiled, errs := r.compiler.Compile(policy, exceptions)
	if len(errs) != 0 {
		logging.V(4).Info("failed to compile policy", "policy", policy.GetName(), "errors", errs)
		return ctrl.Result{}, errs.ToAggregate()
	}
	actions := sets.New(policy.GetSpec().ValidationActions()...)
	// Keep the policy and all of its autogenerated variants together under the policy's own key.
	// Storing autogen variants under separate, policy-independent keys (their autogen ref, e.g.
	// "defaults"/"cronjobs") let two policies overwrite each other's variants and leaked them on
	// delete (issue #16729); a per-policy slice removes with a single delete and cannot collide.
	policies := []Policy{{
		CompiledPolicy: compiled,
		Policy:         policy,
		Exceptions:     exceptions,
		Actions:        actions,
	}}
	for config, p := range autogeneratedIvPols {
		autogenPolicy := policy.DeepCopyObject().(policiesv1beta1.ImageValidatingPolicyLike)
		*autogenPolicy.GetSpec() = *p.Spec
		compiled, errs := r.compiler.Compile(autogenPolicy, exceptions)
		if len(errs) != 0 {
			logging.V(4).Info("failed to compile autogenerated policy", "policy", policy.GetName(), "errors", errs)
			return ctrl.Result{}, errs.ToAggregate()
		}
		policies = append(policies, Policy{
			CompiledPolicy: compiled,
			Policy:         autogenPolicy,
			Exceptions:     exceptions,
			Actions:        actions,
			ExtractionMode: config == ivpolautogen.ExtractionReplacementsRef,
		})
	}
	r.lock.Lock()
	defer r.lock.Unlock()
	r.policies[req.NamespacedName.String()] = policies
	return ctrl.Result{}, nil
}

func (r *reconciler) Fetch(ctx context.Context) ([]Policy, error) {
	r.lock.RLock()
	defer r.lock.RUnlock()
	policies := make([]Policy, 0, len(r.policies))
	for _, value := range r.policies {
		policies = append(policies, value...)
	}
	return policies, nil
}
