package engine

import (
	"context"
	"strings"
	"testing"

	policiesv1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// fakeClient serves a fixed set of ImageValidatingPolicies by name so the reconciler can be driven
// without an API server.
type fakeClient struct {
	client.Client
	policies map[string]*policiesv1beta1.ImageValidatingPolicy
}

func (f *fakeClient) Get(_ context.Context, key client.ObjectKey, obj client.Object, _ ...client.GetOption) error {
	if p, ok := f.policies[key.Name]; ok {
		if o, ok := obj.(*policiesv1beta1.ImageValidatingPolicy); ok {
			*o = *p
			return nil
		}
	}
	return apierrors.NewNotFound(schema.GroupResource{}, key.Name)
}

// autogennablePolicy is a cluster ImageValidatingPolicy matching Pods on CREATE, which triggers
// autogen for pod controllers (Deployments, CronJobs, ...).
func autogennablePolicy(name string) *policiesv1beta1.ImageValidatingPolicy {
	return &policiesv1beta1.ImageValidatingPolicy{
		ObjectMeta: metav1.ObjectMeta{Name: name},
		Spec: policiesv1beta1.ImageValidatingPolicySpec{
			MatchConstraints: &admissionregistrationv1.MatchResources{
				ResourceRules: []admissionregistrationv1.NamedRuleWithOperations{{
					RuleWithOperations: admissionregistrationv1.RuleWithOperations{
						Operations: []admissionregistrationv1.OperationType{admissionregistrationv1.Create},
						Rule: admissionregistrationv1.Rule{
							APIGroups:   []string{""},
							APIVersions: []string{"v1"},
							Resources:   []string{"pods"},
						},
					},
				}},
			},
		},
	}
}

// targetsDeployments reports whether a compiled policy entry matches Deployments, i.e. it is an
// autogen pod-controller variant.
func targetsDeployments(p Policy) bool {
	mc := p.Policy.GetSpec().MatchConstraints
	if mc == nil {
		return false
	}
	for _, rule := range mc.ResourceRules {
		for _, res := range rule.Resources {
			if strings.Contains(res, "deployments") {
				return true
			}
		}
	}
	return false
}

// deploymentVariantsByPolicy counts, per policy name, how many entries in the fetched set target
// Deployments.
func deploymentVariantsByPolicy(policies []Policy) map[string]int {
	out := map[string]int{}
	for _, p := range policies {
		if targetsDeployments(p) {
			out[p.Policy.GetName()]++
		}
	}
	return out
}

// TestReconcile_TwoPolicies_DoNotClobberAutogenVariants is the regression test for issue #16729: two
// autogennable ImageValidatingPolicies must each keep their own autogenerated pod-controller variants.
// Before the fix, the reconciler stored every policy's variants under shared global keys ("/defaults",
// "/cronjobs"), so the second policy's variants overwrote the first's and its image verification was
// silently skipped for Deployments and other workload controllers.
func TestReconcile_TwoPolicies_DoNotClobberAutogenVariants(t *testing.T) {
	ctx := context.Background()
	alpha := autogennablePolicy("alpha")
	beta := autogennablePolicy("beta")

	rec := newReconciler(
		&fakeClient{policies: map[string]*policiesv1beta1.ImageValidatingPolicy{
			"alpha": alpha,
			"beta":  beta,
		}},
		nil, false,
	)

	_, err := rec.Reconcile(ctx, reconcile.Request{NamespacedName: types.NamespacedName{Name: "alpha"}})
	require.NoError(t, err)
	_, err = rec.Reconcile(ctx, reconcile.Request{NamespacedName: types.NamespacedName{Name: "beta"}})
	require.NoError(t, err)

	fetched, err := rec.Fetch(ctx)
	require.NoError(t, err)

	variants := deploymentVariantsByPolicy(fetched)
	assert.Equal(t, 1, variants["alpha"], "alpha must keep its own Deployment autogen variant")
	assert.Equal(t, 1, variants["beta"], "beta must keep its own Deployment autogen variant")
}

// TestReconcile_DeleteRemovesAllVariants covers the leak side of the same bug: deleting a policy must
// remove its autogenerated variants too, not just the primary entry.
func TestReconcile_DeleteRemovesAllVariants(t *testing.T) {
	ctx := context.Background()
	fc := &fakeClient{policies: map[string]*policiesv1beta1.ImageValidatingPolicy{
		"alpha": autogennablePolicy("alpha"),
	}}
	rec := newReconciler(fc, nil, false)

	_, err := rec.Reconcile(ctx, reconcile.Request{NamespacedName: types.NamespacedName{Name: "alpha"}})
	require.NoError(t, err)
	fetched, err := rec.Fetch(ctx)
	require.NoError(t, err)
	require.NotEmpty(t, fetched, "alpha should be present after reconcile")

	// Delete alpha (the fake client now returns NotFound for it).
	delete(fc.policies, "alpha")
	_, err = rec.Reconcile(ctx, reconcile.Request{NamespacedName: types.NamespacedName{Name: "alpha"}})
	require.NoError(t, err)

	fetched, err = rec.Fetch(ctx)
	require.NoError(t, err)
	assert.Empty(t, fetched, "deleting a policy must remove its primary entry and all autogen variants")
}
