package engine

import (
	"context"
	"sync"

	policiesv1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	"github.com/kyverno/kyverno/pkg/cel/engine"
	ivpolautogen "github.com/kyverno/kyverno/pkg/cel/policies/ivpol/autogen"
	policiesv1beta1listers "github.com/kyverno/kyverno/pkg/client/listers/policies.kyverno.io/v1beta1"
	"golang.org/x/exp/maps"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/sets"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type reconciler struct {
	client       client.Client
	lock         *sync.RWMutex
	policies     map[string]Policy
	polexLister  policiesv1beta1listers.PolicyExceptionLister
	polexEnabled bool
}

func newReconciler(
	client client.Client,
	polexLister policiesv1beta1listers.PolicyExceptionLister,
	polexEnabled bool,
) *reconciler {
	return &reconciler{
		client:       client,
		lock:         &sync.RWMutex{},
		policies:     map[string]Policy{},
		polexLister:  polexLister,
		polexEnabled: polexEnabled,
	}
}

func (r *reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	var policy policiesv1beta1.ImageValidatingPolicyLike
	if req.NamespacedName.Namespace == "" {
		var ivp policiesv1beta1.ImageValidatingPolicy
		err := r.client.Get(ctx, req.NamespacedName, &ivp)
		if err != nil {
			if errors.IsNotFound(err) {
				r.lock.Lock()
				defer r.lock.Unlock()
				delete(r.policies, req.NamespacedName.String())
				return ctrl.Result{}, nil
			}
			return ctrl.Result{}, err
		}
		policy = &ivp
	} else {
		var nivp policiesv1beta1.NamespacedImageValidatingPolicy
		err := r.client.Get(ctx, req.NamespacedName, &nivp)
		if err != nil {
			if errors.IsNotFound(err) {
				r.lock.Lock()
				defer r.lock.Unlock()
				delete(r.policies, req.NamespacedName.String())
				return ctrl.Result{}, nil
			}
			return ctrl.Result{}, err
		}
		policy = &nivp
	}
	var exceptions []*policiesv1beta1.PolicyException
	var err error
	if r.polexEnabled {
		exceptions, err = engine.ListExceptions(r.polexLister, policy.GetKind(), policy.GetName())
		if err != nil {
			return ctrl.Result{}, err
		}
	}
	autogeneratedIvPols, err := ivpolautogen.Autogen(policy)
	if err != nil {
		return ctrl.Result{}, err
	}
	r.lock.Lock()
	defer r.lock.Unlock()
	actions := sets.New(policy.GetSpec().ValidationActions()...)
	r.policies[req.NamespacedName.String()] = Policy{
		Policy:     policy,
		Exceptions: exceptions,
		Actions:    actions,
	}
	for name, p := range autogeneratedIvPols {
		namespacedName := types.NamespacedName{
			Name: name,
		}
		autogenPolicy := policy.DeepCopyObject().(policiesv1beta1.ImageValidatingPolicyLike)
		*autogenPolicy.GetSpec() = *p.Spec
		r.policies[namespacedName.String()] = Policy{
			Policy:     autogenPolicy,
			Exceptions: exceptions,
			Actions:    actions,
		}
	}
	return ctrl.Result{}, nil
}

func (r *reconciler) Fetch(ctx context.Context) ([]Policy, error) {
	r.lock.RLock()
	defer r.lock.RUnlock()
	return maps.Values(r.policies), nil
}
