package engine

import (
	"context"
	"fmt"
	"testing"

	policiesv1alpha1 "github.com/kyverno/api/api/policies.kyverno.io/v1alpha1"
	policiesv1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	"github.com/kyverno/kyverno/pkg/cel/libs"
	"github.com/kyverno/kyverno/pkg/cel/matching"
	"github.com/kyverno/kyverno/pkg/config"
	engineapi "github.com/kyverno/kyverno/pkg/engine/api"
	eval "github.com/kyverno/kyverno/pkg/image/verification/evaluator"
	"github.com/kyverno/sdk/extensions/imagedataloader"
	"github.com/stretchr/testify/require"
	admissionv1 "k8s.io/api/admission/v1"
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/validation/field"
	"k8s.io/utils/ptr"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

type countingCompiler struct {
	eval.Compiler
	calls  int
	failAt int
}

func (c *countingCompiler) Compile(p policiesv1beta1.ImageValidatingPolicyLike, exceptions []*policiesv1beta1.PolicyException) (eval.CompiledPolicy, field.ErrorList) {
	c.calls++
	if c.calls == c.failAt {
		return nil, field.ErrorList{field.InternalError(field.NewPath("spec"), fmt.Errorf("test compilation failure"))}
	}
	return c.Compiler.Compile(p, exceptions)
}

func TestMissingCompiledPolicyReturnsPolicyError(t *testing.T) {
	for _, extraction := range []bool{false, true} {
		t.Run(fmt.Sprint(extraction), func(t *testing.T) {
			policy := reusablePolicy()
			provider := ProviderFunc(func(context.Context) ([]Policy, error) {
				return []Policy{{Policy: policy, ExtractionMode: extraction}}, nil
			})
			e := reusableEngine(provider)
			response, err := e.HandleValidating(context.Background(), reuseRequest(), nil)
			require.NoError(t, err)
			require.Len(t, response.Policies, 1)
			require.Equal(t, engineapi.RuleStatusError, response.Policies[0].Result.Status())
			require.Contains(t, response.Policies[0].Result.Message(), "compiled policy is missing")
			if !extraction {
				response, patches, err := e.HandleMutating(context.Background(), reuseRequest(), nil)
				require.NoError(t, err)
				require.Empty(t, patches)
				require.Len(t, response.Policies, 1)
				require.Equal(t, engineapi.RuleStatusError, response.Policies[0].Result.Status())
				require.Contains(t, response.Policies[0].Result.Message(), "compiled policy is missing")
			}
		})
	}
}

func TestReconcileRetriesCompilationFailures(t *testing.T) {
	for _, failAt := range []int{1, 2} {
		t.Run(fmt.Sprint(failAt), func(t *testing.T) {
			c := &countingCompiler{Compiler: eval.NewCompiler(nil)}
			policy := reusablePolicy()
			client := &fakeClient{policies: map[string]*policiesv1beta1.ImageValidatingPolicy{policy.Name: policy}}
			r := newReconciler(c, client, nil, false)
			request := reconcile.Request{NamespacedName: types.NamespacedName{Name: policy.Name}}
			_, err := r.Reconcile(context.Background(), request)
			require.NoError(t, err)
			previous, err := r.Fetch(context.Background())
			require.NoError(t, err)
			require.Greater(t, len(previous), 1, "exercise autogenerated compilation too")
			updated := policy.DeepCopy()
			updated.Spec.Validations[0].Expression = "false"
			client.policies[policy.Name] = updated
			c.failAt = c.calls + failAt
			_, err = r.Reconcile(context.Background(), request)
			require.ErrorContains(t, err, "test compilation failure")
			retained, err := r.Fetch(context.Background())
			require.NoError(t, err)
			require.Equal(t, previous, retained, "failed compilation must not publish partial variants")
			_, err = r.Reconcile(context.Background(), request)
			require.NoError(t, err)
			response, err := reusableEngine(r).HandleValidating(context.Background(), reuseRequest(), nil)
			require.NoError(t, err)
			require.Len(t, response.Policies, 1)
			require.Equal(t, engineapi.RuleStatusFail, response.Policies[0].Result.Status())
		})
	}
}

func reusablePolicy() *policiesv1beta1.ImageValidatingPolicy {
	p := autogennablePolicy("reuse")
	p.Spec.ValidationConfigurations = policiesv1alpha1.ValidationConfiguration{VerifyDigest: ptr.To(false), Required: ptr.To(false)}
	p.Spec.MatchImageReferences = []policiesv1beta1.MatchImageReference{{Glob: "*"}}
	p.Spec.Validations = []admissionregistrationv1.Validation{{Expression: "images.containers.size() == 1"}}
	return p
}

func reuseRequest() EngineRequest {
	return EngineRequest{
		Request: admissionv1.AdmissionRequest{
			Operation:       admissionv1.Create,
			Kind:            metav1.GroupVersionKind{Version: "v1", Kind: "Pod"},
			Resource:        metav1.GroupVersionResource{Version: "v1", Resource: "pods"},
			RequestResource: &metav1.GroupVersionResource{Version: "v1", Resource: "pods"},
			Object:          runtime.RawExtension{Raw: []byte(pod)},
		},
		Context: libs.NewFakeContextProvider(),
	}
}

func reusableEngine(provider Provider) *engineImpl {
	e := NewEngine(provider, nsResolver, matching.NewMatcher(), nil, nil, config.NewDefaultConfiguration(false)).(*engineImpl)
	e.newImageContext = func() (imagedataloader.ImageContext, error) { return fakeImageContext{}, nil }
	return e
}

func TestProviderReusesCompilationAcrossAdmissions(t *testing.T) {
	c := &countingCompiler{Compiler: eval.NewCompiler(nil)}
	provider, err := NewProvider(c, []policiesv1beta1.ImageValidatingPolicyLike{reusablePolicy()}, nil)
	require.NoError(t, err)
	entries, err := provider.Fetch(context.Background())
	require.NoError(t, err)
	require.Equal(t, len(entries), c.calls)
	initial := c.calls
	e := reusableEngine(provider)
	for range 100 {
		response, err := e.HandleValidating(context.Background(), reuseRequest(), nil)
		require.NoError(t, err)
		require.Len(t, response.Policies, 1)
		require.Equal(t, engineapi.RuleStatusPass, response.Policies[0].Result.Status())
		_, _, err = e.HandleMutating(context.Background(), reuseRequest(), nil)
		require.NoError(t, err)
	}
	require.Equal(t, initial, c.calls, "admissions must only evaluate previously compiled programs")
}

func TestReconcileReplacesCompiledPolicies(t *testing.T) {
	c := &countingCompiler{Compiler: eval.NewCompiler(nil)}
	policy := reusablePolicy()
	client := &fakeClient{policies: map[string]*policiesv1beta1.ImageValidatingPolicy{policy.Name: policy}}
	r := newReconciler(c, client, nil, false)
	request := reconcile.Request{NamespacedName: types.NamespacedName{Name: policy.Name}}
	_, err := r.Reconcile(context.Background(), request)
	require.NoError(t, err)
	initial := c.calls
	require.Positive(t, initial)
	e := reusableEngine(r)
	response, err := e.HandleValidating(context.Background(), reuseRequest(), nil)
	require.NoError(t, err)
	require.Equal(t, engineapi.RuleStatusPass, response.Policies[0].Result.Status())
	for range 100 {
		_, err := e.HandleValidating(context.Background(), reuseRequest(), nil)
		require.NoError(t, err)
		_, _, err = e.HandleMutating(context.Background(), reuseRequest(), nil)
		require.NoError(t, err)
	}
	require.Equal(t, initial, c.calls, "reconciled policies must not compile during admission")
	policy = policy.DeepCopy()
	policy.Spec.Validations[0].Expression = "false"
	client.policies[policy.Name] = policy
	_, err = r.Reconcile(context.Background(), request)
	require.NoError(t, err)
	require.Equal(t, 2*initial, c.calls)
	response, err = e.HandleValidating(context.Background(), reuseRequest(), nil)
	require.NoError(t, err)
	require.Equal(t, engineapi.RuleStatusFail, response.Policies[0].Result.Status())
	delete(client.policies, policy.Name)
	_, err = r.Reconcile(context.Background(), request)
	require.NoError(t, err)
	entries, err := r.Fetch(context.Background())
	require.NoError(t, err)
	require.Empty(t, entries)
	require.Equal(t, 2*initial, c.calls)
}

func BenchmarkReusedAdmission(b *testing.B) {
	provider, err := NewProvider(eval.NewCompiler(nil), []policiesv1beta1.ImageValidatingPolicyLike{reusablePolicy()}, nil)
	if err != nil {
		b.Fatal(err)
	}
	e := reusableEngine(provider)
	request := reuseRequest()
	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		if _, err := e.HandleValidating(context.Background(), request, nil); err != nil {
			b.Fatal(err)
		}
	}
}

type reusableExceptionLister struct {
	exceptions []*policiesv1beta1.PolicyException
}

func (l *reusableExceptionLister) List(labels.Selector) ([]*policiesv1beta1.PolicyException, error) {
	return l.exceptions, nil
}

func TestReconcileRecompilesExceptions(t *testing.T) {
	policy := reusablePolicy()
	policy.Spec.Validations[0].Expression = "false"
	c := &countingCompiler{Compiler: eval.NewCompiler(nil)}
	lister := &reusableExceptionLister{}
	r := newReconciler(c, &fakeClient{policies: map[string]*policiesv1beta1.ImageValidatingPolicy{policy.Name: policy}}, lister, true)
	request := reconcile.Request{NamespacedName: types.NamespacedName{Name: policy.Name}}
	_, err := r.Reconcile(context.Background(), request)
	require.NoError(t, err)
	initial := c.calls
	e := reusableEngine(r)
	response, err := e.HandleValidating(context.Background(), reuseRequest(), nil)
	require.NoError(t, err)
	require.Equal(t, engineapi.RuleStatusFail, response.Policies[0].Result.Status())
	lister.exceptions = []*policiesv1beta1.PolicyException{{
		ObjectMeta: metav1.ObjectMeta{Name: "exception"},
		Spec: policiesv1beta1.PolicyExceptionSpec{
			PolicyRefs:      []policiesv1beta1.PolicyRef{{Name: policy.Name, Kind: policy.GetKind()}},
			MatchConditions: []admissionregistrationv1.MatchCondition{{Name: "all", Expression: "true"}},
		},
	}}
	_, err = r.Reconcile(context.Background(), request)
	require.NoError(t, err)
	require.Equal(t, 2*initial, c.calls)
	response, err = e.HandleValidating(context.Background(), reuseRequest(), nil)
	require.NoError(t, err)
	require.Equal(t, engineapi.RuleStatusSkip, response.Policies[0].Result.Status())
	lister.exceptions = nil
	_, err = r.Reconcile(context.Background(), request)
	require.NoError(t, err)
	response, err = e.HandleValidating(context.Background(), reuseRequest(), nil)
	require.NoError(t, err)
	require.Equal(t, engineapi.RuleStatusFail, response.Policies[0].Result.Status())
	require.Equal(t, 3*initial, c.calls)
}
