/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2alpha1

// CredentialsApplyConfiguration represents an declarative configuration of the Credentials type for use
// with apply.
type CredentialsApplyConfiguration struct {
	AllowInsecureRegistry *bool    `json:"allowInsecureRegistry,omitempty"`
	Secrets               []string `json:"secrets,omitempty"`
}

// CredentialsApplyConfiguration constructs an declarative configuration of the Credentials type for use with
// apply.
func Credentials() *CredentialsApplyConfiguration {
	return &CredentialsApplyConfiguration{}
}

// WithAllowInsecureRegistry sets the AllowInsecureRegistry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowInsecureRegistry field is set to the value of the last call.
func (b *CredentialsApplyConfiguration) WithAllowInsecureRegistry(value bool) *CredentialsApplyConfiguration {
	b.AllowInsecureRegistry = &value
	return b
}

// WithSecrets adds the given value to the Secrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Secrets field.
func (b *CredentialsApplyConfiguration) WithSecrets(values ...string) *CredentialsApplyConfiguration {
	for i := range values {
		b.Secrets = append(b.Secrets, values[i])
	}
	return b
}
