# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Install tools
description: Install tools

inputs:
  k6:
    description: Install k6
    default: 'false'
  helm:
    description: Install Helm
    default: 'false'
  cosign:
    description: Install Cosign
    default: 'false'
  yq:
    description: Install yq
    default: 'false'
  kind:
    description: Install Kind (Kubernetes in Docker)
    default: 'false'
  ko:
    description: Install ko (container image builder for Go)
    default: 'false'
  crane:
    description: Install crane (container image tool)
    default: 'false'
  chainsaw:
    description: Install Chainsaw (E2E test runner)
    default: 'false'
  oras:
    description: Install ORAS (OCI Registry As Storage)
    default: 'false'

runs:
  using: composite
  steps:
    - if: inputs.k6 != 'false'
      uses: ./.github/actions/tools/k6
    - if: inputs.helm != 'false'
      uses: ./.github/actions/tools/helm
    - if: inputs.cosign != 'false'
      uses: ./.github/actions/tools/cosign
    - if: inputs.yq != 'false'
      uses: ./.github/actions/tools/yq
    - if: inputs.kind != 'false'
      uses: ./.github/actions/tools/kind
    - if: inputs.ko != 'false'
      uses: ./.github/actions/tools/ko
    - if: inputs.crane != 'false'
      uses: ./.github/actions/tools/crane
    - if: inputs.chainsaw != 'false'
      uses: ./.github/actions/tools/chainsaw
    - if: inputs.oras != 'false'
      uses: ./.github/actions/tools/oras
