package trace

import (
	"fmt"
	"strings"

	"github.com/google/cel-go/cel"
	celast "github.com/google/cel-go/common/ast"
	"github.com/google/cel-go/common/types"
	"github.com/google/cel-go/common/types/ref"
)

type NodeTrace struct {
	Expression string
	Value      string
	Error      string
}

type ExpressionTrace struct {
	Source string
	Nodes  []NodeTrace
	Result string
	// LoopValuesOmitted is set when nodes inside a loop body (all, exists, exists_one, map,
	// filter) ran but were left out of Nodes; see Build for why.
	LoopValuesOmitted bool
}

func Build(source string, ast *cel.Ast, result ref.Val, details *cel.EvalDetails) ExpressionTrace {
	et := ExpressionTrace{
		Source: source,
		Result: stringify(result),
	}
	if details == nil || ast == nil {
		return et
	}
	state := details.State()
	if state == nil {
		return et
	}
	native := ast.NativeRep()
	sourceInfo := native.SourceInfo()

	// loopBody holds the nodes of every loop condition and loop step, which run once per item.
	// cel-go keeps one value per node, the one from its last run, so a body node would show the
	// last item's value next to a result decided by another item (e.g. the second container's
	// image beside the first container's name). Until values are recorded per iteration, they are
	// left out. The loop's iteration range (the list itself) and the loop's own overall result run
	// once and are kept. PreOrderVisit reaches a loop before its body, so the set is filled first.
	// loopInit holds each loop's accumulator start value (e.g. the [] that map() builds into):
	// generated by the macro, not written by the policy author, so never traced.
	loopBody := map[int64]struct{}{}
	loopInit := map[int64]struct{}{}
	celast.PreOrderVisit(native.Expr(), celast.NewExprVisitor(func(e celast.Expr) {
		if e.Kind() == celast.ComprehensionKind {
			loop := e.AsComprehension()
			for _, part := range []celast.Expr{loop.LoopCondition(), loop.LoopStep()} {
				celast.PreOrderVisit(part, celast.NewExprVisitor(func(n celast.Expr) {
					loopBody[n.ID()] = struct{}{}
				}))
			}
			celast.PreOrderVisit(loop.AccuInit(), celast.NewExprVisitor(func(n celast.Expr) {
				loopInit[n.ID()] = struct{}{}
			}))
		}
		if _, ok := loopInit[e.ID()]; ok {
			return
		}
		if _, ok := loopBody[e.ID()]; ok {
			if _, ran := state.Value(e.ID()); ran && e.Kind() != celast.LiteralKind && !referencesMacroInternal(e) {
				et.LoopValuesOmitted = true
			}
			return
		}
		if e.Kind() == celast.LiteralKind {
			// a literal's value is its own text, so tracing it only adds noise
			return
		}
		val, ok := state.Value(e.ID())
		if !ok {
			// this node never evaluated (e.g. short-circuited by &&/||), nothing to trace
			return
		}
		text, err := cel.ExprToString(e, sourceInfo)
		if err != nil || text == "" {
			return
		}
		if strings.Contains(text, "@") && referencesMacroInternal(e) {
			// all()/exists() and friends expand into helper nodes such as @result; they are
			// noise to a reader. The macro call itself renders without them and is kept.
			return
		}
		nt := NodeTrace{Expression: text}
		if types.IsError(val) {
			nt.Error = stringify(val)
		} else {
			nt.Value = stringify(val)
		}
		et.Nodes = append(et.Nodes, nt)
	}))
	return et
}

// referencesMacroInternal reports whether e mentions one of the synthetic identifiers (prefixed
// with @) that macro expansion introduces. Checking for the identifier rather than a bare "@"
// keeps nodes that merely contain an @ inside a string literal.
func referencesMacroInternal(e celast.Expr) bool {
	found := false
	celast.PreOrderVisit(e, celast.NewExprVisitor(func(n celast.Expr) {
		if n.Kind() == celast.IdentKind && strings.HasPrefix(n.AsIdent(), "@") {
			found = true
		}
	}))
	return found
}

func stringify(v ref.Val) string {
	if v == nil {
		return ""
	}
	return fmt.Sprintf("%v", v.Value())
}

type NamedExpressionTrace struct {
	Name string
	ExpressionTrace
}

type ScopeTrace struct {
	Applied bool
	Reason  string
}

const (
	VerdictPass  = "PASS"
	VerdictFail  = "FAIL"
	VerdictError = "ERROR"
	// VerdictSkip means the policy did not reach a pass/fail decision: a match condition
	// excluded the resource, its constraints did not match, or an exception exempted it.
	VerdictSkip = "SKIP"
)

type VerdictTrace struct {
	Status string
	ExpressionTrace
	Message string
}

type Decision struct {
	PolicyName        string
	PolicyKind        string
	ResourceKind      string
	ResourceName      string
	ResourceNamespace string

	Scope     ScopeTrace
	Match     []NamedExpressionTrace
	Variables []NamedExpressionTrace
	Verdict   VerdictTrace
}
