# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Install Helm
description: Install Helm

runs:
  using: composite
  steps:
    - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
    - shell: bash
      run: |
        set -e
        echo "HELM=$(which helm)" >> $GITHUB_ENV
