/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	policieskyvernoiov1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NamespacedGeneratingPolicyLister helps list NamespacedGeneratingPolicies.
// All objects returned here must be treated as read-only.
type NamespacedGeneratingPolicyLister interface {
	// List lists all NamespacedGeneratingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*policieskyvernoiov1beta1.NamespacedGeneratingPolicy, err error)
	// NamespacedGeneratingPolicies returns an object that can list and get NamespacedGeneratingPolicies.
	NamespacedGeneratingPolicies(namespace string) NamespacedGeneratingPolicyNamespaceLister
	NamespacedGeneratingPolicyListerExpansion
}

// namespacedGeneratingPolicyLister implements the NamespacedGeneratingPolicyLister interface.
type namespacedGeneratingPolicyLister struct {
	listers.ResourceIndexer[*policieskyvernoiov1beta1.NamespacedGeneratingPolicy]
}

// NewNamespacedGeneratingPolicyLister returns a new NamespacedGeneratingPolicyLister.
func NewNamespacedGeneratingPolicyLister(indexer cache.Indexer) NamespacedGeneratingPolicyLister {
	return &namespacedGeneratingPolicyLister{listers.New[*policieskyvernoiov1beta1.NamespacedGeneratingPolicy](indexer, policieskyvernoiov1beta1.Resource("namespacedgeneratingpolicy"))}
}

// NamespacedGeneratingPolicies returns an object that can list and get NamespacedGeneratingPolicies.
func (s *namespacedGeneratingPolicyLister) NamespacedGeneratingPolicies(namespace string) NamespacedGeneratingPolicyNamespaceLister {
	return namespacedGeneratingPolicyNamespaceLister{listers.NewNamespaced[*policieskyvernoiov1beta1.NamespacedGeneratingPolicy](s.ResourceIndexer, namespace)}
}

// NamespacedGeneratingPolicyNamespaceLister helps list and get NamespacedGeneratingPolicies.
// All objects returned here must be treated as read-only.
type NamespacedGeneratingPolicyNamespaceLister interface {
	// List lists all NamespacedGeneratingPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*policieskyvernoiov1beta1.NamespacedGeneratingPolicy, err error)
	// Get retrieves the NamespacedGeneratingPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*policieskyvernoiov1beta1.NamespacedGeneratingPolicy, error)
	NamespacedGeneratingPolicyNamespaceListerExpansion
}

// namespacedGeneratingPolicyNamespaceLister implements the NamespacedGeneratingPolicyNamespaceLister
// interface.
type namespacedGeneratingPolicyNamespaceLister struct {
	listers.ResourceIndexer[*policieskyvernoiov1beta1.NamespacedGeneratingPolicy]
}
