package gpol

import (
	"context"
	"fmt"
	"slices"
	"strings"
	"sync"
	"sync/atomic"

	"github.com/go-logr/logr"
	"github.com/kyverno/kyverno/api/kyverno"
	kyvernov1 "github.com/kyverno/kyverno/api/kyverno/v1"
	"github.com/kyverno/kyverno/pkg/background/common"
	"github.com/kyverno/kyverno/pkg/clients/dclient"
	reportutils "github.com/kyverno/kyverno/pkg/utils/report"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/restmapper"
	"k8s.io/client-go/tools/cache"
	watchTools "k8s.io/client-go/tools/watch"
)

// Resource holds a cached view of a downstream resource.
type Resource struct {
	Name      string
	Namespace string
	Hash      string
	Labels    map[string]string
	Data      *unstructured.Unstructured
}

// WatchManager tracks downstream resources generated by gpol policies and reconciles
// their lifecycle (sync, delete, recreate) through per-GVR dynamic watchers.
type WatchManager struct {
	client     dclient.Interface
	restMapper meta.RESTMapper

	// dynamicWatchers maps a GVR to the active watcher for that resource kind.
	dynamicWatchers map[schema.GroupVersionResource]*watcher
	// policyRefs maps a policy name to the set of GVRs it generates resources for.
	policyRefs map[string][]schema.GroupVersionResource
	// refCount tracks the number of policies producing resources of a given GVR.
	refCount map[schema.GroupVersionResource]int

	log           logr.Logger
	lock          sync.Mutex
	bootstrapping atomic.Bool // prevents concurrent Bootstrap runs (e.g. rapid sync toggle)
}

type watcher struct {
	watcher       watch.Interface
	metadataCache map[types.UID]Resource
}

func NewWatchManager(log logr.Logger, client dclient.Interface) *WatchManager {
	apiGroupResources, _ := restmapper.GetAPIGroupResources(client.GetKubeClient().Discovery())
	return &WatchManager{
		log:             log,
		client:          client,
		restMapper:      restmapper.NewDiscoveryRESTMapper(apiGroupResources),
		dynamicWatchers: make(map[schema.GroupVersionResource]*watcher),
		policyRefs:      make(map[string][]schema.GroupVersionResource),
		refCount:        make(map[schema.GroupVersionResource]int),
	}
}

func (wm *WatchManager) trackResource(obj *unstructured.Unstructured, gvr schema.GroupVersionResource) {
	w, ok := wm.dynamicWatchers[gvr]
	if !ok {
		return
	}
	cp := obj.DeepCopy()
	w.metadataCache[cp.GetUID()] = Resource{
		Name:      cp.GetName(),
		Namespace: cp.GetNamespace(),
		Labels:    cp.GetLabels(),
		Hash:      reportutils.CalculateResourceHash(*cp),
		Data:      cp,
	}
}

func (wm *WatchManager) untrackResource(uid types.UID, gvr schema.GroupVersionResource) {
	if w, ok := wm.dynamicWatchers[gvr]; ok {
		delete(w.metadataCache, uid)
	}
}

// SyncWatchers ensures a watcher is running for every GVR referenced by generatedResources,
// updates ref-counts, and tears down watchers for GVRs the policy no longer produces.
func (wm *WatchManager) SyncWatchers(policyName string, generatedResources []*unstructured.Unstructured) error {
	// A nil slice means "no authoritative result for this run" (e.g. a concurrent UR
	// whose engine found the downstream already up-to-date, or matchConditions filtered
	// out the trigger) and must not tear down watchers another run just started.
	// A non-nil empty slice means the policy now legitimately generates nothing and
	// should be reconciled to an empty managed set (watchers torn down).
	if generatedResources == nil {
		return nil
	}

	// Phase 1 — under lock: resolve GVRs and identify which ones still need a watcher.
	wm.lock.Lock()

	newGVRs := make(map[schema.GroupVersionResource]struct{}, len(generatedResources))
	var toStart []schema.GroupVersionResource

	for _, res := range generatedResources {
		gvk := res.GroupVersionKind()
		mapping, err := wm.restMapper.RESTMapping(gvk.GroupKind(), gvk.Version)
		if err != nil {
			wm.lock.Unlock()
			return fmt.Errorf("failed to get REST mapping for %s: %w", gvk, err)
		}
		gvr := mapping.Resource
		newGVRs[gvr] = struct{}{}
		if wm.dynamicWatchers[gvr] == nil {
			toStart = append(toStart, gvr)
		}
	}

	wm.lock.Unlock()

	// Phase 2 — outside lock: start new watchers (involves a List API call per GVR).
	// startWatcher returns the watcher and a startLoop func; the goroutine is NOT
	// started here so that Phase 3 can seed the correct cache before any events fire.
	type pendingWatcher struct {
		w         *watcher
		startLoop func()
	}
	pending := make(map[schema.GroupVersionResource]pendingWatcher, len(toStart))
	for _, gvr := range toStart {
		w, startLoop, err := wm.startWatcher(gvr)
		if err != nil {
			for _, pw := range pending {
				pw.w.watcher.Stop()
			}
			return err
		}
		pending[gvr] = pendingWatcher{w, startLoop}
	}

	// Phase 3 — under lock: register new watchers and reconcile policy state.
	wm.lock.Lock()

	var loopsToStart []func()
	for gvr, pw := range pending {
		if wm.dynamicWatchers[gvr] != nil {
			// A concurrent SyncWatchers call already registered one; discard ours.
			pw.w.watcher.Stop()
		} else {
			wm.dynamicWatchers[gvr] = pw.w
			// Clear the stale initialCache seeded by the List in Phase 2. Phase 3's
			// trackResource calls below will set the correct desired state so that
			// events buffered between the List and goroutine start are compared against
			// the right hashes and do not trigger spurious reverts.
			pw.w.metadataCache = make(map[types.UID]Resource)
			loopsToStart = append(loopsToStart, pw.startLoop)
		}
	}

	// Refresh metadataCache entries for each generated resource.
	// Resources returned by the engine carry the correct management labels (the
	// genCtx mutex guarantees that) and the real cluster UID (the context now
	// fetches existing resources instead of appending the bare input object).
	// This corrects any stale cache entries left by a prior race, and seeds the
	// correct desired state for newly started watchers before their goroutine fires.
	for _, res := range generatedResources {
		if res.GetUID() == "" {
			continue
		}
		gvk := res.GroupVersionKind()
		mapping, err := wm.restMapper.RESTMapping(gvk.GroupKind(), gvk.Version)
		if err != nil {
			continue
		}
		wm.trackResource(res, mapping.Resource)
	}

	oldGVRs := wm.policyRefs[policyName]

	for gvr := range newGVRs {
		if !slices.Contains(oldGVRs, gvr) {
			wm.refCount[gvr]++
		}
	}

	// Tear down GVRs that this policy no longer generates resources for.
	for _, oldGVR := range oldGVRs {
		if _, stillActive := newGVRs[oldGVR]; stillActive {
			continue
		}
		wm.refCount[oldGVR]--
		wm.deleteDownstreamsForPolicy(policyName, oldGVR)
		if wm.refCount[oldGVR] <= 0 {
			if w := wm.dynamicWatchers[oldGVR]; w != nil {
				w.watcher.Stop()
			}
			delete(wm.dynamicWatchers, oldGVR)
			delete(wm.refCount, oldGVR)
		}
	}

	wm.policyRefs[policyName] = make([]schema.GroupVersionResource, 0, len(newGVRs))
	for gvr := range newGVRs {
		wm.policyRefs[policyName] = append(wm.policyRefs[policyName], gvr)
	}

	wm.lock.Unlock()

	// Start goroutines after releasing the lock so that handleAdd/handleUpdate/handleDelete
	// can acquire it. Events buffered in the RetryWatcher channel during Phase 2→Phase 3
	// are processed against the correct cache set above, not the stale List seed.
	for _, startLoop := range loopsToStart {
		startLoop()
	}

	return nil
}

// deleteDownstreamsForPolicy deletes all cached resources generated by policyName
// within the given GVR. Caller must hold wm.lock.
func (wm *WatchManager) deleteDownstreamsForPolicy(policyName string, gvr schema.GroupVersionResource) {
	w, ok := wm.dynamicWatchers[gvr]
	if !ok {
		return
	}
	logger := wm.log.WithValues("gvr", gvr, "policy", policyName)
	for uid, res := range w.metadataCache {
		if res.Labels[common.GeneratePolicyLabel] != policyName {
			continue
		}
		logger.V(4).Info("deleting downstream resource", "kind", res.Data.GetKind(), "name", res.Name, "namespace", res.Namespace)
		err := wm.client.DeleteResource(context.TODO(), res.Data.GetAPIVersion(), res.Data.GetKind(), res.Namespace, res.Name, false, metav1.DeleteOptions{})
		if err != nil {
			logger.Error(err, "failed to delete downstream resource", "name", res.Name)
		} else {
			logger.V(4).Info("downstream resource deleted", "name", res.Name, "namespace", res.Namespace)
			delete(w.metadataCache, uid)
		}
	}
}

// GetDownstreams returns a snapshot of all downstream resources generated by the given policy.
func (wm *WatchManager) GetDownstreams(policyName string) []*unstructured.Unstructured {
	wm.lock.Lock()
	defer wm.lock.Unlock()

	logger := wm.log.WithValues("policy", policyName)
	logger.V(4).Info("listing downstream resources")

	gvrList, ok := wm.policyRefs[policyName]
	if !ok {
		logger.V(4).Info("no watchers registered for policy")
		return nil
	}

	var out []*unstructured.Unstructured
	for _, gvr := range gvrList {
		w, ok := wm.dynamicWatchers[gvr]
		if !ok {
			continue
		}
		for _, res := range w.metadataCache {
			if res.Labels[common.GeneratePolicyLabel] != policyName {
				continue
			}
			logger.V(4).Info("found downstream", "kind", res.Data.GetKind(), "name", res.Name, "namespace", res.Namespace)
			out = append(out, res.Data.DeepCopy())
		}
	}
	return out
}

// DeleteDownstreams deletes generated resources for a policy, optionally scoped to a trigger.
// Pass trigger == nil to delete all downstreams regardless of which trigger produced them.
// It does not stop the watchers.
func (wm *WatchManager) DeleteDownstreams(policyName string, trigger *kyvernov1.ResourceSpec) {
	wm.lock.Lock()
	defer wm.lock.Unlock()

	logger := wm.log.WithValues("policy", policyName)
	logger.V(2).Info("deleting downstream resources")

	gvrList, ok := wm.policyRefs[policyName]
	if !ok {
		return
	}

	for _, gvr := range gvrList {
		w, ok := wm.dynamicWatchers[gvr]
		if !ok {
			continue
		}
		logger := logger.WithValues("gvr", gvr)

		var toDelete []types.UID
		for uid, res := range w.metadataCache {
			if res.Labels[common.GeneratePolicyLabel] != policyName {
				continue
			}
			if trigger != nil && res.Labels[common.GenerateTriggerUIDLabel] != string(trigger.UID) {
				continue
			}
			toDelete = append(toDelete, uid)
		}

		for _, uid := range toDelete {
			res := w.metadataCache[uid]
			logger.V(4).Info("deleting downstream resource", "kind", res.Data.GetKind(), "name", res.Name, "namespace", res.Namespace)
			err := wm.client.DeleteResource(context.TODO(), res.Data.GetAPIVersion(), res.Data.GetKind(), res.Namespace, res.Name, false, metav1.DeleteOptions{})
			if err != nil {
				logger.Error(err, "failed to delete downstream resource", "name", res.Name)
			} else {
				logger.V(4).Info("downstream resource deleted", "name", res.Name, "namespace", res.Namespace)
				wm.untrackResource(uid, gvr)
			}
		}
	}
}

// RemoveWatchersForPolicy removes all state for a policy. If deleteDownstream is true,
// resources generated from scratch (without a source) are also deleted from the cluster.
func (wm *WatchManager) RemoveWatchersForPolicy(policyName string, deleteDownstream bool) {
	wm.lock.Lock()
	defer wm.lock.Unlock()

	logger := wm.log.WithValues("policy", policyName)
	logger.V(2).Info("clearing policy watcher state")

	gvrList, ok := wm.policyRefs[policyName]
	if !ok {
		logger.V(4).Info("no watchers registered for policy")
		return
	}

	for _, gvr := range gvrList {
		w, ok := wm.dynamicWatchers[gvr]
		if !ok {
			continue
		}
		logger := logger.WithValues("gvr", gvr)

		var toRemove []types.UID
		for uid, res := range w.metadataCache {
			if res.Labels[common.GeneratePolicyLabel] == policyName {
				toRemove = append(toRemove, uid)
			}
		}

		for _, uid := range toRemove {
			res := w.metadataCache[uid]
			if deleteDownstream {
				if _, hasSource := res.Labels[common.GenerateSourceUIDLabel]; !hasSource {
					logger.V(4).Info("deleting downstream resource", "kind", res.Data.GetKind(), "name", res.Name, "namespace", res.Namespace)
					err := wm.client.DeleteResource(context.TODO(), res.Data.GetAPIVersion(), res.Data.GetKind(), res.Namespace, res.Name, false, metav1.DeleteOptions{})
					if err != nil {
						logger.Error(err, "failed to delete downstream resource", "name", res.Name)
					} else {
						logger.V(4).Info("downstream resource deleted", "name", res.Name, "namespace", res.Namespace)
					}
				}
			}
			wm.untrackResource(uid, gvr)
		}

		wm.refCount[gvr]--
		if wm.refCount[gvr] <= 0 {
			logger.V(3).Info("stopping watcher, no remaining references")
			w.watcher.Stop()
			delete(wm.dynamicWatchers, gvr)
			delete(wm.refCount, gvr)
		}
	}
	delete(wm.policyRefs, policyName)
}

// StopWatchers stops all watchers and resets internal state.
func (wm *WatchManager) StopWatchers() {
	wm.lock.Lock()
	defer wm.lock.Unlock()

	for _, w := range wm.dynamicWatchers {
		w.watcher.Stop()
	}
	wm.dynamicWatchers = make(map[schema.GroupVersionResource]*watcher)
	wm.policyRefs = make(map[string][]schema.GroupVersionResource)
	wm.refCount = make(map[schema.GroupVersionResource]int)
}

// startWatcher starts a list+watch for gvr and seeds the cache from the initial list.
// It returns the watcher and a startLoop function that launches the event-processing
// goroutine. The caller is responsible for calling startLoop after the watcher's
// metadataCache has been initialised to the correct desired state, so that events
// buffered between the List and the goroutine start are compared against the right
// hashes and do not trigger spurious reverts.
func (wm *WatchManager) startWatcher(gvr schema.GroupVersionResource) (*watcher, func(), error) {
	logger := wm.log.WithValues("gvr", gvr)

	// Use the same label selector for the seed List as Bootstrap uses, so the API
	// server filters out non-downstream objects (EphemeralReports, etc.) server-side
	// instead of transferring them over the wire and discarding them client-side.
	labelFilter := kyverno.LabelAppManagedBy + "=" + kyverno.ValueKyvernoApp + "," + common.GeneratePolicyLabel
	list, err := wm.client.GetDynamicInterface().Resource(gvr).List(context.TODO(), metav1.ListOptions{
		LabelSelector: labelFilter,
	})
	if err != nil {
		return nil, nil, fmt.Errorf("failed to list %s for watcher seed: %w", gvr, err)
	}

	initialCache := make(map[types.UID]Resource, len(list.Items))
	for i := range list.Items {
		obj := &list.Items[i]
		cp := obj.DeepCopy()
		initialCache[cp.GetUID()] = Resource{
			Name:      cp.GetName(),
			Namespace: cp.GetNamespace(),
			Labels:    cp.GetLabels(),
			Hash:      reportutils.CalculateResourceHash(*cp),
			Data:      cp,
		}
	}

	listRV := list.GetResourceVersion()
	if listRV == "" {
		listRV = "0"
	}
	logger.V(2).Info("starting watcher", "listRV", listRV, "seeded", len(initialCache))

	watchFunc := func(opts metav1.ListOptions) (watch.Interface, error) {
		opts.LabelSelector = labelFilter
		return wm.client.GetDynamicInterface().Resource(gvr).Watch(context.Background(), opts)
	}
	wi, err := watchTools.NewRetryWatcherWithContext(context.TODO(), listRV, &cache.ListWatch{WatchFunc: watchFunc})
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create retry watcher for %s: %w", gvr, err)
	}

	w := &watcher{watcher: wi, metadataCache: initialCache}

	startLoop := func() {
		go func() {
			defer logger.V(2).Info("watcher stopped")
			for event := range wi.ResultChan() {
				obj, ok := event.Object.(*unstructured.Unstructured)
				if !ok {
					if event.Type == watch.Error {
						logger.Error(fmt.Errorf("watch error event"), "received watch error", "object", event.Object)
					}
					continue
				}
				switch event.Type {
				case watch.Added:
					wm.handleAdd(obj, gvr)
				case watch.Modified:
					wm.handleUpdate(obj, gvr)
				case watch.Deleted:
					wm.handleDelete(obj, gvr)
				case watch.Error:
					logger.Error(fmt.Errorf("watch error event"), "received watch error", "object", event.Object)
				}
			}
		}()
	}

	return w, startLoop, nil
}

func (wm *WatchManager) handleAdd(obj *unstructured.Unstructured, gvr schema.GroupVersionResource) {
	if obj.GetLabels()[kyverno.LabelAppManagedBy] != kyverno.ValueKyvernoApp {
		return
	}
	if obj.GetLabels()[common.GeneratePolicyLabel] == "" {
		return
	}
	wm.lock.Lock()
	defer wm.lock.Unlock()
	wm.trackResource(obj, gvr)
	wm.log.V(4).Info("tracked added downstream", "name", obj.GetName(), "namespace", obj.GetNamespace(), "uid", obj.GetUID())
}

func (wm *WatchManager) handleUpdate(obj *unstructured.Unstructured, gvr schema.GroupVersionResource) {
	wm.lock.Lock()
	defer wm.lock.Unlock()

	w, ok := wm.dynamicWatchers[gvr]
	if !ok {
		return
	}

	uid := obj.GetUID()
	managedByKyverno := obj.GetLabels()[kyverno.LabelAppManagedBy] == kyverno.ValueKyvernoApp

	if managedByKyverno {
		cached, tracked := w.metadataCache[uid]
		if !tracked {
			// Resource is not in the desired-state cache.  Do NOT speculatively
			// re-track it here: a stale watch event buffered just before
			// RemoveWatchersForPolicy cleared the cache would otherwise re-seed a
			// stale hash, causing the engine-update event that follows to trigger a
			// spurious revert.  SyncWatchers (called synchronously in the UR goroutine
			// right after the engine runs) is the sole authoritative writer for this
			// policy's entries; it will seed the correct hash before any subsequent
			// event is processed.
			wm.log.V(4).Info("untracked downstream on update, skipping", "name", obj.GetName(), "namespace", obj.GetNamespace())
			return
		}
		if reportutils.CalculateResourceHash(*obj) == cached.Hash {
			wm.trackResource(obj, gvr)
			return
		}
		// Content diverged from desired state — revert it.
		wm.log.V(2).Info("downstream modified, reverting",
			"policy", cached.Labels[common.GeneratePolicyLabel],
			"target", fmt.Sprintf("%s/%s/%s/%s", obj.GetAPIVersion(), obj.GetKind(), obj.GetNamespace(), obj.GetName()))
		desired := cached.Data.DeepCopy()
		desired.SetUID("")
		desired.SetSelfLink("")
		desired.SetCreationTimestamp(metav1.Time{})
		desired.SetManagedFields(nil)
		desired.SetResourceVersion("")
		updated, err := wm.client.UpdateResource(context.TODO(), desired.GetAPIVersion(), desired.GetKind(), desired.GetNamespace(), desired, false)
		if err != nil {
			wm.log.Error(err, "failed to revert downstream", "name", obj.GetName(), "namespace", obj.GetNamespace())
		} else {
			wm.trackResource(updated, gvr)
			wm.log.V(2).Info("downstream reverted",
				"policy", cached.Labels[common.GeneratePolicyLabel],
				"target", fmt.Sprintf("%s/%s/%s/%s", obj.GetAPIVersion(), obj.GetKind(), obj.GetNamespace(), obj.GetName()))
		}
		return
	}

	// Source resource updated — propagate changes to synced downstreams.
	source := obj.DeepCopy()
	source.SetUID("")
	source.SetSelfLink("")
	source.SetCreationTimestamp(metav1.Time{})
	source.SetManagedFields(nil)
	source.SetResourceVersion("")

	selector := &metav1.LabelSelector{
		MatchLabels: map[string]string{common.GenerateSourceUIDLabel: string(uid)},
	}
	downstreams, err := wm.client.ListResource(context.TODO(), obj.GetAPIVersion(), obj.GetKind(), "", selector)
	if err != nil {
		wm.log.Error(err, "failed to list downstreams for source update", "name", obj.GetName())
		return
	}

	for i := range downstreams.Items {
		ds := &downstreams.Items[i]
		if _, tracked := w.metadataCache[ds.GetUID()]; !tracked {
			continue
		}
		newObj := &unstructured.Unstructured{}
		newObj.SetUnstructuredContent(source.UnstructuredContent())
		newObj.SetName(ds.GetName())
		newObj.SetNamespace(ds.GetNamespace())
		newObj.SetKind(ds.GetKind())
		newObj.SetAPIVersion(ds.GetAPIVersion())
		newObj.SetLabels(ds.GetLabels())
		updated, err := wm.client.UpdateResource(context.TODO(), ds.GetAPIVersion(), ds.GetKind(), ds.GetNamespace(), newObj, false)
		if err != nil {
			wm.log.Error(err, "failed to propagate source update to downstream", "name", ds.GetName(), "namespace", ds.GetNamespace())
		} else {
			wm.trackResource(updated, gvr)
			wm.log.V(2).Info("propagated source update to downstream",
				"policy", ds.GetLabels()[common.GeneratePolicyLabel],
				"target", fmt.Sprintf("%s/%s/%s/%s", ds.GetAPIVersion(), ds.GetKind(), ds.GetNamespace(), ds.GetName()))
		}
	}
}

func (wm *WatchManager) handleDelete(obj *unstructured.Unstructured, gvr schema.GroupVersionResource) {
	wm.lock.Lock()
	defer wm.lock.Unlock()

	w, ok := wm.dynamicWatchers[gvr]
	if !ok {
		return
	}

	uid := obj.GetUID()
	managedByKyverno := obj.GetLabels()[kyverno.LabelAppManagedBy] == kyverno.ValueKyvernoApp

	if !managedByKyverno {
		// Source resource deleted — clean up its downstreams.
		wm.log.V(2).Info("source deleted, removing downstreams",
			"kind", obj.GetKind(), "name", obj.GetName(), "namespace", obj.GetNamespace())
		selector := &metav1.LabelSelector{
			MatchLabels: map[string]string{common.GenerateSourceUIDLabel: string(uid)},
		}
		downstreams, err := wm.client.ListResource(context.TODO(), obj.GetAPIVersion(), obj.GetKind(), "", selector)
		if err != nil {
			wm.log.Error(err, "failed to list downstreams for source delete", "name", obj.GetName())
			return
		}
		for _, ds := range downstreams.Items {
			if _, tracked := w.metadataCache[ds.GetUID()]; !tracked {
				continue
			}
			err := wm.client.DeleteResource(context.TODO(), ds.GetAPIVersion(), ds.GetKind(), ds.GetNamespace(), ds.GetName(), false, metav1.DeleteOptions{})
			if err != nil {
				wm.log.Error(err, "failed to delete downstream", "name", ds.GetName(), "namespace", ds.GetNamespace())
			} else {
				wm.log.V(2).Info("downstream deleted (source removed)",
					"policy", ds.GetLabels()[common.GeneratePolicyLabel],
					"target", fmt.Sprintf("%s/%s/%s/%s", ds.GetAPIVersion(), ds.GetKind(), ds.GetNamespace(), ds.GetName()))
				wm.untrackResource(ds.GetUID(), gvr)
			}
		}
		return
	}

	// Kyverno-managed resource deleted — recreate it if we have a desired state cached.
	cached, ok := w.metadataCache[uid]
	if !ok {
		wm.log.V(4).Info("deleted resource not in cache, skipping recreate", "name", obj.GetName(), "namespace", obj.GetNamespace())
		return
	}

	wm.untrackResource(uid, gvr)

	wm.log.V(2).Info("downstream deleted, recreating",
		"policy", cached.Labels[common.GeneratePolicyLabel],
		"target", fmt.Sprintf("%s/%s/%s/%s", cached.Data.GetAPIVersion(), cached.Data.GetKind(), cached.Namespace, cached.Name))
	desired := cached.Data.DeepCopy()
	desired.SetUID("")
	desired.SetSelfLink("")
	desired.SetCreationTimestamp(metav1.Time{})
	desired.SetManagedFields(nil)
	desired.SetResourceVersion("")

	_, err := wm.client.CreateResource(context.TODO(), desired.GetAPIVersion(), desired.GetKind(), desired.GetNamespace(), desired, false)
	if err != nil {
		wm.log.Error(err, "failed to recreate downstream",
			"policy", cached.Labels[common.GeneratePolicyLabel],
			"target", fmt.Sprintf("%s/%s/%s/%s", cached.Data.GetAPIVersion(), cached.Data.GetKind(), cached.Namespace, cached.Name))
		w.metadataCache[uid] = cached
	} else {
		wm.log.V(2).Info("downstream recreated",
			"policy", cached.Labels[common.GeneratePolicyLabel],
			"target", fmt.Sprintf("%s/%s/%s/%s", cached.Data.GetAPIVersion(), cached.Data.GetKind(), cached.Namespace, cached.Name))
	}
}

// Bootstrap scans the cluster for existing downstream resources and restores watchers.
// It should be called once at startup so the watch manager is not blind after a pod restart.
// Concurrent calls (e.g. from rapid synchronize enable/disable toggles) are collapsed into
// one: if a bootstrap is already in progress the second call returns immediately.
func (wm *WatchManager) Bootstrap(ctx context.Context) {
	if !wm.bootstrapping.CompareAndSwap(false, true) {
		wm.log.V(4).Info("bootstrap: already in progress, skipping")
		return
	}
	defer wm.bootstrapping.Store(false)

	wm.log.V(2).Info("bootstrap: scanning cluster for existing downstream resources")

	_, resourceLists, err := wm.client.GetKubeClient().Discovery().ServerGroupsAndResources()
	if err != nil {
		// Partial failure is normal when some API groups are temporarily unavailable.
		wm.log.V(2).Info("bootstrap: partial discovery error, some GVRs may be skipped", "err", err)
	}

	// Both labels are required to skip internal Kyverno objects (EphemeralReports, etc.)
	// that carry managed-by=kyverno but are not downstream generated resources.
	labelFilter := kyverno.LabelAppManagedBy + "=" + kyverno.ValueKyvernoApp + "," + common.GeneratePolicyLabel

	for _, rl := range resourceLists {
		gv, err := schema.ParseGroupVersion(rl.GroupVersion)
		if err != nil {
			continue
		}
		for _, apiRes := range rl.APIResources {
			// Skip sub-resources and types that don't support list/watch.
			if strings.Contains(apiRes.Name, "/") ||
				!slices.Contains(apiRes.Verbs, "list") ||
				!slices.Contains(apiRes.Verbs, "watch") {
				continue
			}

			gvr := gv.WithResource(apiRes.Name)

			wm.lock.Lock()
			alreadyWatched := wm.dynamicWatchers[gvr] != nil
			wm.lock.Unlock()
			if alreadyWatched {
				continue
			}

			// Cheap probe: are there kyverno-managed resources of this GVR?
			list, err := wm.client.GetDynamicInterface().Resource(gvr).List(ctx, metav1.ListOptions{
				LabelSelector: labelFilter,
			})
			if err != nil || len(list.Items) == 0 {
				continue
			}

			w, startLoop, err := wm.startWatcher(gvr)
			if err != nil {
				wm.log.Error(err, "bootstrap: failed to start watcher", "gvr", gvr)
				continue
			}

			wm.lock.Lock()
			if wm.dynamicWatchers[gvr] != nil {
				// A concurrent SyncWatchers call registered one while we were starting ours.
				w.watcher.Stop()
				wm.lock.Unlock()
				continue
			}
			wm.dynamicWatchers[gvr] = w

			// Rebuild policyRefs and refCount from resource labels so that
			// DeleteDownstreams / RemoveWatchersForPolicy work correctly.
			for _, item := range list.Items {
				policyName := item.GetLabels()[common.GeneratePolicyLabel]
				if policyName == "" {
					continue
				}
				if !slices.Contains(wm.policyRefs[policyName], gvr) {
					wm.policyRefs[policyName] = append(wm.policyRefs[policyName], gvr)
					wm.refCount[gvr]++
				}
			}
			wm.lock.Unlock()

			// Bootstrap seeds from the cluster's current state (initialCache from the
			// List is already the correct desired state), so start the goroutine now.
			startLoop()

			wm.log.V(2).Info("bootstrap: watcher restored", "gvr", gvr, "resources", len(list.Items))
		}
	}

	wm.log.V(2).Info("bootstrap: complete")
}

