# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Install Kind
description: Install Kind (Kubernetes in Docker) CLI

runs:
  using: composite
  steps:
    - id: kind
      uses: helm/kind-action@06c1ae10762d3b9c1644e7fe69596ae519e015a2 # v1.15.0
      with:
        install_only: true
    - shell: bash
      run: |
        set -e
        echo "KIND=$(which kind)" >> $GITHUB_ENV
