package libs

import (
	"testing"

	"github.com/kyverno/kyverno/pkg/clients/dclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

func generateTestRESTMapper() meta.RESTMapper {
	gvs := []schema.GroupVersion{
		{Group: "", Version: "v1"},
		{Group: "rbac.authorization.k8s.io", Version: "v1"},
		{Group: "networking.k8s.io", Version: "v1"},
	}
	m := meta.NewDefaultRESTMapper(gvs)
	m.Add(schema.GroupVersionKind{Group: "", Version: "v1", Kind: "ConfigMap"}, meta.RESTScopeNamespace)
	m.Add(schema.GroupVersionKind{Group: "rbac.authorization.k8s.io", Version: "v1", Kind: "ClusterRoleBinding"}, meta.RESTScopeRoot)
	m.Add(schema.GroupVersionKind{Group: "networking.k8s.io", Version: "v1", Kind: "IngressClass"}, meta.RESTScopeRoot)
	return m
}

func clusterRoleBinding() map[string]any {
	return map[string]any{
		"apiVersion": "rbac.authorization.k8s.io/v1",
		"kind":       "ClusterRoleBinding",
		"metadata":   map[string]any{"name": "escalate"},
	}
}

// A namespaced policy passes its own namespace as the apply() argument, which
// satisfies the namespace-boundary check, but a cluster-scoped resource still
// escapes that namespace. It must be rejected.
func TestGenerateResources_NamespacedPolicyRejectsClusterScoped(t *testing.T) {
	cp := &contextProvider{
		cliEvaluation: true,
		restMapper:    generateTestRESTMapper(),
	}

	err := cp.GenerateResources("tenant-ns", []map[string]any{clusterRoleBinding()})
	assert.Error(t, err, "namespaced policy must not generate a cluster-scoped resource")
	assert.Contains(t, err.Error(), "cross-scope generation denied")
	assert.Empty(t, cp.GetGeneratedResources())
}

// A namespaced resource generated into the policy namespace is still allowed.
func TestGenerateResources_NamespacedPolicyAllowsNamespaced(t *testing.T) {
	cp := &contextProvider{
		cliEvaluation: true,
		restMapper:    generateTestRESTMapper(),
	}

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err := cp.GenerateResources("tenant-ns", []map[string]any{cm})
	assert.NoError(t, err)
	assert.Len(t, cp.GetGeneratedResources(), 1)
	assert.Equal(t, "tenant-ns", cp.GetGeneratedResources()[0].GetNamespace())
}

// A cluster-scoped policy uses an empty namespace argument and may still
// generate cluster-scoped resources.
func TestGenerateResources_ClusterPolicyAllowsClusterScoped(t *testing.T) {
	cp := &contextProvider{
		cliEvaluation: true,
		restMapper:    generateTestRESTMapper(),
	}

	err := cp.GenerateResources("", []map[string]any{clusterRoleBinding()})
	assert.NoError(t, err)
	assert.Len(t, cp.GetGeneratedResources(), 1)
	assert.Empty(t, cp.GetGeneratedResources()[0].GetNamespace())
}

// Regression test for kyverno/kyverno#15722: when the target resource was
// already generated by an earlier UR (e.g. a resync, a retry, or a
// cacheRestore pass), GenerateResources must still report it via
// GetGeneratedResources(). Callers such as WatchManager.SyncWatchers use an
// empty generated-resources list to mean "this policy no longer generates
// anything" and tear down the corresponding watcher/downstream resource. If
// an already-existing resource were silently dropped here, a concurrent UR
// for the same policy (created for a different trigger) would race in and
// delete a resource another UR had just legitimately created.
func TestGenerateResources_ExistingResourceReportedAsGenerated(t *testing.T) {
	existing := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "data",
				"namespace": "tenant-ns",
			},
		},
	}
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	require.Len(t, cp.GetGeneratedResources(), 1)
	assert.Equal(t, "data", cp.GetGeneratedResources()[0].GetName())
	assert.Equal(t, "tenant-ns", cp.GetGeneratedResources()[0].GetNamespace())
}

// Companion case: restoreCache mode must not create the resource, but if it
// already exists it still needs to be reported so the watch manager's cache
// gets restored (the original purpose of cacheRestore, see
// kyverno/kyverno#13571).
func TestGenerateResources_RestoreCacheReportsExistingButDoesNotCreate(t *testing.T) {
	existing := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "data",
				"namespace": "tenant-ns",
			},
		},
	}
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.genCtx.restoreCache = true

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	require.Len(t, cp.GetGeneratedResources(), 1)
	assert.Equal(t, "data", cp.GetGeneratedResources()[0].GetName())

	notYetCreated := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "not-yet-created", "namespace": "tenant-ns"},
	}
	cp.ClearGeneratedResources()
	err = cp.GenerateResources("tenant-ns", []map[string]any{notYetCreated})
	require.NoError(t, err)
	assert.Empty(t, cp.GetGeneratedResources(), "restoreCache must not create resources that don't exist yet")
	_, err = fakeClient.GetResource(t.Context(), "v1", "ConfigMap", "tenant-ns", "not-yet-created")
	assert.Error(t, err, "restoreCache must not create resources that don't exist yet")
}
