package libs

import (
	"context"
	"fmt"
	"testing"

	"github.com/kyverno/kyverno/api/kyverno"
	"github.com/kyverno/kyverno/pkg/background/common"
	"github.com/kyverno/kyverno/pkg/clients/dclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

func generateTestRESTMapper() meta.RESTMapper {
	gvs := []schema.GroupVersion{
		{Group: "", Version: "v1"},
		{Group: "rbac.authorization.k8s.io", Version: "v1"},
		{Group: "networking.k8s.io", Version: "v1"},
	}
	m := meta.NewDefaultRESTMapper(gvs)
	m.Add(schema.GroupVersionKind{Group: "", Version: "v1", Kind: "ConfigMap"}, meta.RESTScopeNamespace)
	m.Add(schema.GroupVersionKind{Group: "rbac.authorization.k8s.io", Version: "v1", Kind: "ClusterRoleBinding"}, meta.RESTScopeRoot)
	m.Add(schema.GroupVersionKind{Group: "networking.k8s.io", Version: "v1", Kind: "IngressClass"}, meta.RESTScopeRoot)
	return m
}

func clusterRoleBinding() map[string]any {
	return map[string]any{
		"apiVersion": "rbac.authorization.k8s.io/v1",
		"kind":       "ClusterRoleBinding",
		"metadata":   map[string]any{"name": "escalate"},
	}
}

// A namespaced policy passes its own namespace as the apply() argument, which
// satisfies the namespace-boundary check, but a cluster-scoped resource still
// escapes that namespace. It must be rejected.
func TestGenerateResources_NamespacedPolicyRejectsClusterScoped(t *testing.T) {
	cp := &contextProvider{
		cliEvaluation: true,
		restMapper:    generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-ngpol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)

	err := cp.GenerateResources("tenant-ns", []map[string]any{clusterRoleBinding()})
	assert.Error(t, err, "namespaced policy must not generate a cluster-scoped resource")
	assert.Contains(t, err.Error(), "cross-scope generation denied")
	assert.Empty(t, cp.GetGeneratedResources())
}

// A namespaced resource generated into the policy namespace is still allowed.
func TestGenerateResources_NamespacedPolicyAllowsNamespaced(t *testing.T) {
	cp := &contextProvider{
		cliEvaluation: true,
		restMapper:    generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-ngpol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err := cp.GenerateResources("tenant-ns", []map[string]any{cm})
	assert.NoError(t, err)
	assert.Len(t, cp.GetGeneratedResources(), 1)
	assert.Equal(t, "tenant-ns", cp.GetGeneratedResources()[0].GetNamespace())
}

// A cluster-scoped policy uses an empty namespace argument and may still
// generate cluster-scoped resources.
func TestGenerateResources_ClusterPolicyAllowsClusterScoped(t *testing.T) {
	cp := &contextProvider{
		cliEvaluation: true,
		restMapper:    generateTestRESTMapper(),
	}

	err := cp.GenerateResources("", []map[string]any{clusterRoleBinding()})
	assert.NoError(t, err)
	assert.Len(t, cp.GetGeneratedResources(), 1)
	assert.Empty(t, cp.GetGeneratedResources()[0].GetNamespace())
}

// Regression test for kyverno/kyverno#15722: when the target resource was
// already generated by an earlier UR (e.g. a resync, a retry, or a
// cacheRestore pass), GenerateResources must still report it via
// GetGeneratedResources(). Callers such as WatchManager.SyncWatchers use an
// empty generated-resources list to mean "this policy no longer generates
// anything" and tear down the corresponding watcher/downstream resource. If
// an already-existing resource were silently dropped here, a concurrent UR
// for the same policy (created for a different trigger) would race in and
// delete a resource another UR had just legitimately created.
func TestGenerateResources_ExistingResourceReportedAsGenerated(t *testing.T) {
	existing := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "data",
				"namespace": "tenant-ns",
				"labels": map[string]any{
					kyverno.LabelAppManagedBy:           kyverno.ValueKyvernoApp,
					common.GeneratePolicyLabel:          "test-gpol",
					common.GeneratePolicyNamespaceLabel: "tenant-ns",
					common.GenerateTriggerUIDLabel:      "trigger-uid",
				},
			},
		},
	}
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	require.Len(t, cp.GetGeneratedResources(), 1)
	assert.Equal(t, "data", cp.GetGeneratedResources()[0].GetName())
	assert.Equal(t, "tenant-ns", cp.GetGeneratedResources()[0].GetNamespace())
}

// Two different triggers of the same policy must not "adopt" each other's
// downstream resource just because they happen to render the same target
// name/namespace: the existing resource's trigger-UID label has to match the
// trigger currently being processed, not merely the policy name.
func TestGenerateResources_DifferentTriggerExistingResourceNotAdopted(t *testing.T) {
	existing := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "data",
				"namespace": "tenant-ns",
				"labels": map[string]any{
					kyverno.LabelAppManagedBy:      kyverno.ValueKyvernoApp,
					common.GeneratePolicyLabel:     "test-gpol",
					common.GenerateTriggerUIDLabel: "other-trigger-uid",
				},
			},
		},
	}
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	assert.Empty(t, cp.GetGeneratedResources(), "a resource generated for a different trigger of the same policy must not be adopted")
}

// An existing resource that merely shares the same GVK/namespace/name but is
// NOT labeled as managed by this policy (e.g. an unrelated, user-created
// resource) must never be reported as generated -- otherwise it would be
// silently adopted by the policy and become subject to synchronize/delete
// behavior it was never meant to have.
func TestGenerateResources_UnmanagedExistingResourceNotAdopted(t *testing.T) {
	unrelated := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "data",
				"namespace": "tenant-ns",
				// no Kyverno management labels: this is a pre-existing,
				// user-owned resource that just happens to match.
			},
		},
	}
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, unrelated)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	assert.Empty(t, cp.GetGeneratedResources(), "an unmanaged pre-existing resource must not be adopted")
}

// Companion case: restoreCache mode must not create the resource, but if it
// already exists it still needs to be reported so the watch manager's cache
// gets restored (the original purpose of cacheRestore, see
// kyverno/kyverno#13571).
// Regression test for kyverno/kyverno#16742: when the downstream resource
// already exists and is managed by this policy/trigger, a re-evaluation (e.g.
// on a trigger UPDATE with synchronize enabled) must update it in place with
// the newly rendered content instead of deleting and recreating it (or leaving
// it untouched).
func TestGenerateResources_ExistingResourceUpdatedInPlace(t *testing.T) {
	existing := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "data",
				"namespace": "tenant-ns",
				"labels": map[string]any{
					kyverno.LabelAppManagedBy:           kyverno.ValueKyvernoApp,
					common.GeneratePolicyLabel:          "test-gpol",
					common.GeneratePolicyNamespaceLabel: "tenant-ns",
					common.GenerateTriggerUIDLabel:      "trigger-uid",
				},
			},
			"data": map[string]any{"quota": "10"},
		},
	}
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
		"data":       map[string]any{"quota": "50"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	require.Len(t, cp.GetGeneratedResources(), 1)

	updated, err := fakeClient.GetResource(t.Context(), "v1", "ConfigMap", "tenant-ns", "data")
	require.NoError(t, err)
	quota, _, err := unstructured.NestedString(updated.Object, "data", "quota")
	require.NoError(t, err)
	assert.Equal(t, "50", quota, "existing downstream must be updated in place with the newly rendered content")
}

func TestGenerateResources_RestoreCacheReportsExistingButDoesNotCreate(t *testing.T) {
	existing := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "data",
				"namespace": "tenant-ns",
				"labels": map[string]any{
					kyverno.LabelAppManagedBy:           kyverno.ValueKyvernoApp,
					common.GeneratePolicyLabel:          "test-gpol",
					common.GeneratePolicyNamespaceLabel: "tenant-ns",
					common.GenerateTriggerUIDLabel:      "trigger-uid",
				},
			},
		},
	}
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", true, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	require.Len(t, cp.GetGeneratedResources(), 1)
	assert.Equal(t, "data", cp.GetGeneratedResources()[0].GetName())

	notYetCreated := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "not-yet-created", "namespace": "tenant-ns"},
	}
	cp.ClearGeneratedResources()
	err = cp.GenerateResources("tenant-ns", []map[string]any{notYetCreated})
	require.NoError(t, err)
	assert.Empty(t, cp.GetGeneratedResources(), "restoreCache must not create resources that don't exist yet")
	_, err = fakeClient.GetResource(t.Context(), "v1", "ConfigMap", "tenant-ns", "not-yet-created")
	assert.Error(t, err, "restoreCache must not create resources that don't exist yet")
}

// Regression test for kyverno/kyverno#15444: a resource cloned from another
// namespace (e.g. a Secret synced by External Secrets that carries an
// ownerReference to an ExternalSecret CR) must have its ownerReferences
// stripped, otherwise the owner does not exist in the target namespace and
// the garbage collector deletes the generated resource almost immediately.
func TestGenerateResources_CrossNamespaceStripsOwnerReferences(t *testing.T) {
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata": map[string]any{
			"name":              "example",
			"namespace":         "kyverno",
			"uid":               "5b7dc768-9a06-4b25-b3e1-02b0e7b8d02a",
			"resourceVersion":   "12345",
			"creationTimestamp": "2026-01-01T00:00:00Z",
			"managedFields": []any{
				map[string]any{
					"apiVersion": "v1",
					"manager":    "external-secrets",
					"operation":  "Update",
				},
			},
			"ownerReferences": []any{
				map[string]any{
					"apiVersion":         "external-secrets.io/v1",
					"blockOwnerDeletion": true,
					"controller":         true,
					"kind":               "ExternalSecret",
					"name":               "example",
					"uid":                "16401acc-ab37-4b5d-b4e2-fbd6f952f602",
				},
			},
		},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	require.Len(t, cp.GetGeneratedResources(), 1)

	generated := cp.GetGeneratedResources()[0]
	assert.Equal(t, "tenant-ns", generated.GetNamespace())
	assert.Empty(t, generated.GetOwnerReferences(), "cross-namespace generation must strip ownerReferences")
	assert.Nil(t, generated.GetManagedFields(), "server-populated managedFields must not be copied")
	creationTimestamp := generated.GetCreationTimestamp()
	assert.True(t, creationTimestamp.IsZero(), "server-populated creationTimestamp must not be copied")
	assert.Equal(t, "5b7dc768-9a06-4b25-b3e1-02b0e7b8d02a", generated.GetLabels()[common.GenerateSourceUIDLabel],
		"metadata cleanup must not run before addGenerateLabels reads the source UID/resourceVersion")
}

// Companion case: generating into the same namespace as the source must keep
// the ownerReferences intact, as they remain valid there.
func TestGenerateResources_SameNamespaceKeepsOwnerReferences(t *testing.T) {
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata": map[string]any{
			"name":      "example",
			"namespace": "tenant-ns",
			"ownerReferences": []any{
				map[string]any{
					"apiVersion": "external-secrets.io/v1",
					"kind":       "ExternalSecret",
					"name":       "example",
					"uid":        "16401acc-ab37-4b5d-b4e2-fbd6f952f602",
				},
			},
		},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	require.Len(t, cp.GetGeneratedResources(), 1)

	generated := cp.GetGeneratedResources()[0]
	assert.Equal(t, "tenant-ns", generated.GetNamespace())
	require.Len(t, generated.GetOwnerReferences(), 1, "same-namespace generation must keep ownerReferences")
	assert.Equal(t, "ExternalSecret", generated.GetOwnerReferences()[0].Kind)
}

func TestContextProvider_CloneIsolatesPerEvaluationState(t *testing.T) {
	original := &contextProvider{
		generatedResources: []*unstructured.Unstructured{
			{Object: map[string]any{"apiVersion": "v1", "kind": "ConfigMap", "metadata": map[string]any{"name": "orig"}}},
		},
	}
	original.SetGenerateContext("policy-a", "default", "trigger-a", "default", "v1", "", "Pod", "uid-a", true, false, nil)

	cloned := original.Clone()
	clone, ok := cloned.(*contextProvider)
	require.True(t, ok)

	// Clone is for per-worker execution; it must start with isolated mutable state.
	assert.Empty(t, clone.generatedResources)
	assert.Equal(t, original.genCtx, clone.genCtx)

	clone.SetGenerateContext("policy-b", "kube-system", "trigger-b", "kube-system", "v1", "", "Service", "uid-b", false, false, nil)
	clone.generatedResources = append(clone.generatedResources, &unstructured.Unstructured{
		Object: map[string]any{"apiVersion": "v1", "kind": "ConfigMap", "metadata": map[string]any{"name": "clone"}},
	})

	assert.Equal(t, "policy-a", original.genCtx.policyName)
	assert.True(t, original.genCtx.restoreCache)
	require.Len(t, original.generatedResources, 1)
	assert.Equal(t, "orig", original.generatedResources[0].GetName())
}

// ssaTrackingClient wraps dclient.Interface and records whether ApplyResource
// was called, returning the submitted object directly (no strategic merge needed).
type ssaTrackingClient struct {
	dclient.Interface
	applyCalled bool
	applyResult *unstructured.Unstructured
}

func (c *ssaTrackingClient) ApplyResource(_ context.Context, _ string, _ string, _ string, _ string, obj interface{}, _ bool, _ string, _ ...string) (*unstructured.Unstructured, error) {
	c.applyCalled = true
	if u, ok := obj.(*unstructured.Unstructured); ok {
		result := u.DeepCopy()
		c.applyResult = result
		return result, nil
	}
	return nil, fmt.Errorf("unexpected type %T", obj)
}

// TestGenerateResources_ServerSideApply_Create verifies that when
// useServerSideApply is enabled and the resource does not yet exist,
// ApplyResource is called instead of CreateResource.
func TestGenerateResources_ServerSideApply_Create(t *testing.T) {
	base, err := dclient.NewFakeClient(runtime.NewScheme(), nil)
	require.NoError(t, err)
	base.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	mock := &ssaTrackingClient{Interface: base}
	cp := &contextProvider{
		client:     mock,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "", "trigger", "default", "v1", "", "Namespace", "trigger-uid", false, true, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "ssa-cm", "namespace": "default"},
		"data":       map[string]any{"key": "value"},
	}
	err = cp.GenerateResources("default", []map[string]any{cm})
	require.NoError(t, err)
	assert.True(t, mock.applyCalled, "ApplyResource must be called when useServerSideApply=true")
	require.Len(t, cp.GetGeneratedResources(), 1)
	assert.Equal(t, "ssa-cm", cp.GetGeneratedResources()[0].GetName())
}

// TestGenerateResources_ServerSideApply_Update verifies that when
// useServerSideApply is enabled and the resource already exists,
// ApplyResource is called (not GetResource + skip), so the resource is updated.
func TestGenerateResources_ServerSideApply_Update(t *testing.T) {
	existing := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "ssa-cm",
				"namespace": "default",
				"labels": map[string]any{
					kyverno.LabelAppManagedBy:           kyverno.ValueKyvernoApp,
					common.GeneratePolicyLabel:          "test-gpol",
					common.GeneratePolicyNamespaceLabel: "",
					common.GenerateTriggerUIDLabel:      "trigger-uid",
				},
			},
			"data": map[string]any{"old-key": "old-value"},
		},
	}
	base, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	base.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	mock := &ssaTrackingClient{Interface: base}
	cp := &contextProvider{
		client:     mock,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "", "trigger", "default", "v1", "", "Namespace", "trigger-uid", false, true, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "ssa-cm", "namespace": "default"},
		"data":       map[string]any{"new-key": "new-value"},
	}
	err = cp.GenerateResources("default", []map[string]any{cm})
	require.NoError(t, err)
	assert.True(t, mock.applyCalled, "ApplyResource must be called when useServerSideApply=true")
	require.Len(t, cp.GetGeneratedResources(), 1)
	assert.Equal(t, "ssa-cm", cp.GetGeneratedResources()[0].GetName())
}

func TestGenerateResources_ServerSideApply_UnmanagedExistingResourceNotAdopted(t *testing.T) {
	unrelated := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "ssa-cm",
				"namespace": "default",
			},
		},
	}
	base, err := dclient.NewFakeClient(runtime.NewScheme(), nil, unrelated)
	require.NoError(t, err)
	base.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	mock := &ssaTrackingClient{Interface: base}
	cp := &contextProvider{
		client:     mock,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "", "trigger", "default", "v1", "", "Namespace", "trigger-uid", false, true, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "ssa-cm", "namespace": "default"},
	}
	err = cp.GenerateResources("default", []map[string]any{cm})
	require.NoError(t, err)
	assert.False(t, mock.applyCalled, "ApplyResource must not be called for unmanaged pre-existing resources")
	assert.Empty(t, cp.GetGeneratedResources(), "unmanaged pre-existing resources must not be adopted")
}

func TestAddGenerateLabelsStampsPolicyNamespace(t *testing.T) {
	cp := &contextProvider{}
	cp.SetGenerateContext("test-ngpol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)

	obj := &unstructured.Unstructured{Object: map[string]any{"metadata": map[string]any{"name": "down"}}}
	cp.addGenerateLabels(obj)

	assert.Equal(t, "test-ngpol", obj.GetLabels()[common.GeneratePolicyLabel])
	assert.Equal(t, "tenant-ns", obj.GetLabels()[common.GeneratePolicyNamespaceLabel])
}

func TestAddGenerateLabelsLeavesPolicyNamespaceEmptyForClusterPolicy(t *testing.T) {
	cp := &contextProvider{}
	cp.SetGenerateContext("test-gpol", "", "trigger", "default", "v1", "", "Namespace", "trigger-uid", false, false, nil)

	obj := &unstructured.Unstructured{Object: map[string]any{"metadata": map[string]any{"name": "down"}}}
	cp.addGenerateLabels(obj)

	assert.Equal(t, "test-gpol", obj.GetLabels()[common.GeneratePolicyLabel])
	policyNamespace, exists := obj.GetLabels()[common.GeneratePolicyNamespaceLabel]
	assert.True(t, exists, "a cluster-scoped policy must stamp an explicit empty policy-namespace label")
	assert.Empty(t, policyNamespace)
}

func managedDownstream(name, ns, policyName, policyNS, triggerUID string, includeNSKey bool) *unstructured.Unstructured {
	labels := map[string]any{
		kyverno.LabelAppManagedBy:      kyverno.ValueKyvernoApp,
		common.GeneratePolicyLabel:     policyName,
		common.GenerateTriggerUIDLabel: triggerUID,
	}
	if includeNSKey {
		labels[common.GeneratePolicyNamespaceLabel] = policyNS
	}
	return &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":            name,
				"namespace":       ns,
				"uid":             "uid-" + name,
				"resourceVersion": "1",
				"labels":          labels,
			},
		},
	}
}

// contestedIn mirrors the conflict set the gpol engine provider derives from
// the cluster: the namespaces in which a same-named policy of the other scope
// can generate, and where a legacy downstream therefore has no known owner.
func contestedIn(namespaces ...string) map[string]bool {
	conflicts := make(map[string]bool, len(namespaces))
	for _, namespace := range namespaces {
		conflicts[namespace] = true
	}
	return conflicts
}

func TestIsManagedByPolicy_NamespaceAware(t *testing.T) {
	t.Run("cluster genCtx does not adopt resource with policy-namespace=tenant-ns", func(t *testing.T) {
		cp := &contextProvider{}
		cp.SetGenerateContext("pol", "", "trigger", "default", "v1", "", "Namespace", "trigger-uid", false, false, nil)
		obj := managedDownstream("data", "default", "pol", "tenant-ns", "trigger-uid", true)
		assert.False(t, cp.isManagedByPolicy(obj))
	})

	t.Run("namespaced genCtx does not adopt resource with policy-namespace=other-ns", func(t *testing.T) {
		cp := &contextProvider{}
		cp.SetGenerateContext("pol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)
		obj := managedDownstream("data", "tenant-ns", "pol", "other-ns", "trigger-uid", true)
		assert.False(t, cp.isManagedByPolicy(obj))
	})

	t.Run("explicit empty namespace label belongs to cluster only", func(t *testing.T) {
		cluster := &contextProvider{}
		cluster.SetGenerateContext("pol", "", "trigger", "default", "v1", "", "Namespace", "trigger-uid", false, false, nil)
		ngpol := &contextProvider{}
		ngpol.SetGenerateContext("pol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)
		obj := managedDownstream("data", "default", "pol", "", "trigger-uid", true)
		assert.True(t, cluster.isManagedByPolicy(obj))
		assert.False(t, ngpol.isManagedByPolicy(obj))
	})

	t.Run("tenant-ns label belongs to that ngpol only", func(t *testing.T) {
		cluster := &contextProvider{}
		cluster.SetGenerateContext("pol", "", "trigger", "default", "v1", "", "Namespace", "trigger-uid", false, false, nil)
		ngpol := &contextProvider{}
		ngpol.SetGenerateContext("pol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)
		other := &contextProvider{}
		other.SetGenerateContext("pol", "other-ns", "trigger", "other-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)
		obj := managedDownstream("data", "tenant-ns", "pol", "tenant-ns", "trigger-uid", true)
		assert.False(t, cluster.isManagedByPolicy(obj))
		assert.True(t, ngpol.isManagedByPolicy(obj))
		assert.False(t, other.isManagedByPolicy(obj))
	})

	t.Run("missing namespace label is unowned, not cluster", func(t *testing.T) {
		cluster := &contextProvider{}
		cluster.SetGenerateContext("pol", "", "trigger", "default", "v1", "", "Namespace", "trigger-uid", false, false, nil)
		ngpol := &contextProvider{}
		ngpol.SetGenerateContext("pol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)
		obj := managedDownstream("data", "default", "pol", "", "trigger-uid", false)
		assert.False(t, cluster.isManagedByPolicy(obj), "a missing namespace label must not read as cluster ownership")
		assert.False(t, ngpol.isManagedByPolicy(obj))
		assert.True(t, cluster.isLegacyDownstream(obj), "either scope may report it as an unowned legacy resource")
		assert.True(t, ngpol.isLegacyDownstream(obj))
	})

	t.Run("unrelated resources are neither owned nor legacy", func(t *testing.T) {
		cp := &contextProvider{}
		cp.SetGenerateContext("pol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)
		otherPolicy := managedDownstream("data", "tenant-ns", "other-pol", "", "trigger-uid", false)
		otherTrigger := managedDownstream("data", "tenant-ns", "pol", "", "other-trigger-uid", false)
		assert.False(t, cp.isLegacyDownstream(otherPolicy))
		assert.False(t, cp.isLegacyDownstream(otherTrigger))
	})
}

func TestGenerateResources_RestoreCacheMigratesLegacyNamespaceLabel(t *testing.T) {
	existing := managedDownstream("data", "tenant-ns", "test-ngpol", "", "trigger-uid", false)
	legacyLabels := existing.GetLabels()
	legacyLabels[common.GenerateSourceUIDLabel] = "clone-source-uid"
	existing.SetLabels(legacyLabels)
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-ngpol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", true, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	require.Len(t, cp.GetGeneratedResources(), 1)

	updated, err := fakeClient.GetResource(t.Context(), "v1", "ConfigMap", "tenant-ns", "data")
	require.NoError(t, err)
	labels := updated.GetLabels()
	assert.Equal(t, "tenant-ns", labels[common.GeneratePolicyNamespaceLabel],
		"restoreCache must migrate legacy resources by stamping policy-namespace")
	assert.Equal(t, "test-ngpol", labels[common.GeneratePolicyLabel])
	assert.Equal(t, "clone-source-uid", labels[common.GenerateSourceUIDLabel],
		"migration must preserve the clone source UID the watcher resolves downstreams by")
	assert.Equal(t, "tenant-ns", cp.GetGeneratedResources()[0].GetLabels()[common.GeneratePolicyNamespaceLabel])
}

func TestGenerateResources_RestoreCacheClusterDoesNotStealNamespaced(t *testing.T) {
	existing := managedDownstream("data", "default", "pol", "tenant-ns", "trigger-uid", true)
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("pol", "", "trigger", "default", "v1", "", "Namespace", "trigger-uid", true, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "default"},
	}
	err = cp.GenerateResources("default", []map[string]any{cm})
	require.NoError(t, err)
	assert.Empty(t, cp.GetGeneratedResources(), "cluster genCtx must not adopt a resource labeled for tenant-ns")

	still, err := fakeClient.GetResource(t.Context(), "v1", "ConfigMap", "default", "data")
	require.NoError(t, err)
	assert.Equal(t, "tenant-ns", still.GetLabels()[common.GeneratePolicyNamespaceLabel])
}

func TestGenerateResources_RestoreCacheClusterMigratesLegacyEmptyNSLabel(t *testing.T) {
	existing := managedDownstream("data", "default", "pol", "", "trigger-uid", false)
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("pol", "", "trigger", "default", "v1", "", "Namespace", "trigger-uid", true, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "default"},
	}
	err = cp.GenerateResources("default", []map[string]any{cm})
	require.NoError(t, err)
	require.Len(t, cp.GetGeneratedResources(), 1)

	updated, err := fakeClient.GetResource(t.Context(), "v1", "ConfigMap", "default", "data")
	require.NoError(t, err)
	_, hasNS := updated.GetLabels()[common.GeneratePolicyNamespaceLabel]
	assert.True(t, hasNS, "cluster restoreCache should stamp an explicit empty policy-namespace label")
	assert.Equal(t, "", updated.GetLabels()[common.GeneratePolicyNamespaceLabel])
}

func TestGenerateResources_NamespacedDoesNotAdoptExplicitClusterLabel(t *testing.T) {
	existing := managedDownstream("data", "tenant-ns", "pol", "", "trigger-uid", true)
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("pol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	assert.Empty(t, cp.GetGeneratedResources(), "ngpol must not adopt a resource with explicit empty (cluster) namespace label")
}

// A downstream generated before the policy namespace label existed has no
// recorded owner. When a policy with the same name exists in the other scope,
// neither policy may claim it: writing the label would attribute the resource
// by guesswork, and updating it would let one policy overwrite the content of
// the other's downstream. This holds for ordinary evaluations and for the
// cache restore pass alike.
func TestGenerateResources_AmbiguousLegacyDownstreamIsLeftUntouched(t *testing.T) {
	for _, restoreCache := range []bool{false, true} {
		for _, policyNamespace := range []string{"", "tenant-ns"} {
			t.Run(fmt.Sprintf("restoreCache=%t policyNamespace=%q", restoreCache, policyNamespace), func(t *testing.T) {
				existing := managedDownstream("data", "tenant-ns", "pol", "", "trigger-uid", false)
				fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
				require.NoError(t, err)
				fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

				cp := &contextProvider{
					client:     fakeClient,
					restMapper: generateTestRESTMapper(),
				}
				cp.SetGenerateContext("pol", policyNamespace, "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", restoreCache, false, contestedIn("tenant-ns"))

				cm := map[string]any{
					"apiVersion": "v1",
					"kind":       "ConfigMap",
					"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
					"data":       map[string]any{"quota": "50"},
				}
				err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
				require.NoError(t, err)
				assert.Empty(t, cp.GetGeneratedResources(), "an ambiguous legacy downstream must not be reported as generated")

				untouched, err := fakeClient.GetResource(t.Context(), "v1", "ConfigMap", "tenant-ns", "data")
				require.NoError(t, err)
				_, hasNamespaceLabel := untouched.GetLabels()[common.GeneratePolicyNamespaceLabel]
				assert.False(t, hasNamespaceLabel, "ambiguous ownership must not be settled by writing a namespace label")
				data, _, err := unstructured.NestedStringMap(untouched.Object, "data")
				require.NoError(t, err)
				assert.Empty(t, data, "the ambiguous resource must not be updated")
			})
		}
	}
}

// The same ambiguous owner reached from both scopes: whichever policy is
// evaluated first, the legacy downstream must stay untouched, so the outcome
// does not depend on evaluation order.
func TestGenerateResources_AmbiguousLegacyOwnerCollisionIsOrderIndependent(t *testing.T) {
	const namespace = "tenant-ns"
	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": namespace},
		"data":       map[string]any{"quota": "50"},
	}

	for _, order := range [][]string{{"pol", "tenant-ns/pol"}, {"tenant-ns/pol", "pol"}} {
		t.Run(fmt.Sprintf("order=%v", order), func(t *testing.T) {
			existing := managedDownstream("data", namespace, "pol", "", "trigger-uid", false)
			fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
			require.NoError(t, err)
			fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

			for _, key := range order {
				policyNamespace := ""
				if key == "tenant-ns/pol" {
					policyNamespace = namespace
				}
				cp := &contextProvider{
					client:     fakeClient,
					restMapper: generateTestRESTMapper(),
				}
				cp.SetGenerateContext("pol", policyNamespace, "trigger", namespace, "v1", "", "Namespace", "trigger-uid", false, false, contestedIn(namespace))
				require.NoError(t, cp.GenerateResources(namespace, []map[string]any{cm}))
				assert.Empty(t, cp.GetGeneratedResources(), "ambiguous legacy downstream must not be claimed by %s", key)
			}

			final, err := fakeClient.GetResource(t.Context(), "v1", "ConfigMap", namespace, "data")
			require.NoError(t, err)
			_, hasNamespaceLabel := final.GetLabels()[common.GeneratePolicyNamespaceLabel]
			assert.False(t, hasNamespaceLabel, "the first policy evaluated must not settle ambiguous ownership")
		})
	}
}

// Conflict detection is scoped to the namespaces a same-named policy of the
// other scope can generate into. A cluster policy is therefore free to migrate
// a legacy downstream in a namespace that hosts no conflicting policy, and is
// only held back where the competing policy could really have produced it.
func TestGenerateResources_LegacyMigrationOnlyContestsConflictingNamespaces(t *testing.T) {
	const namespace = "tenant-ns"
	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": namespace},
	}

	for _, test := range []struct {
		name      string
		conflicts map[string]bool
		migrated  bool
	}{
		{
			name:      "conflicting policy in another namespace does not block migration here",
			conflicts: contestedIn("other-ns"),
			migrated:  true,
		},
		{
			name:      "conflicting policy in this namespace blocks migration",
			conflicts: contestedIn(namespace),
		},
		{
			name:      "an unknown conflicting namespace blocks migration everywhere",
			conflicts: contestedIn(LegacyOwnerAnyNamespace),
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			existing := managedDownstream("data", namespace, "pol", "", "trigger-uid", false)
			fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
			require.NoError(t, err)
			fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

			cp := &contextProvider{
				client:     fakeClient,
				restMapper: generateTestRESTMapper(),
			}
			cp.SetGenerateContext("pol", "", "trigger", namespace, "v1", "", "Namespace", "trigger-uid", false, false, test.conflicts)

			require.NoError(t, cp.GenerateResources(namespace, []map[string]any{cm}))
			updated, err := fakeClient.GetResource(t.Context(), "v1", "ConfigMap", namespace, "data")
			require.NoError(t, err)
			_, hasNamespaceLabel := updated.GetLabels()[common.GeneratePolicyNamespaceLabel]
			if test.migrated {
				assert.Len(t, cp.GetGeneratedResources(), 1)
				assert.True(t, hasNamespaceLabel, "an uncontested legacy downstream must be migrated")
				assert.Equal(t, "", updated.GetLabels()[common.GeneratePolicyNamespaceLabel])
			} else {
				assert.Empty(t, cp.GetGeneratedResources())
				assert.False(t, hasNamespaceLabel)
			}
		})
	}
}

// With no same-named policy in the other scope the legacy downstream has a
// single possible owner, so it is migrated on any evaluation, not only the
// cache restore pass, and the persisted label is what the watch manager reads.
func TestGenerateResources_UnambiguousLegacyDownstreamMigratedOnUpdate(t *testing.T) {
	existing := managedDownstream("data", "tenant-ns", "test-ngpol", "", "trigger-uid", false)
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-ngpol", "tenant-ns", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false, false, nil)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
		"data":       map[string]any{"quota": "50"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	require.Len(t, cp.GetGeneratedResources(), 1)

	updated, err := fakeClient.GetResource(t.Context(), "v1", "ConfigMap", "tenant-ns", "data")
	require.NoError(t, err)
	assert.Equal(t, "tenant-ns", updated.GetLabels()[common.GeneratePolicyNamespaceLabel],
		"an unambiguous legacy downstream must be migrated on update as well as on restore")
	assert.Equal(t, "test-ngpol", updated.GetLabels()[common.GeneratePolicyLabel])
}
