package libs

import (
	"testing"

	"github.com/kyverno/kyverno/api/kyverno"
	"github.com/kyverno/kyverno/pkg/background/common"
	"github.com/kyverno/kyverno/pkg/clients/dclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

func generateTestRESTMapper() meta.RESTMapper {
	gvs := []schema.GroupVersion{
		{Group: "", Version: "v1"},
		{Group: "rbac.authorization.k8s.io", Version: "v1"},
		{Group: "networking.k8s.io", Version: "v1"},
	}
	m := meta.NewDefaultRESTMapper(gvs)
	m.Add(schema.GroupVersionKind{Group: "", Version: "v1", Kind: "ConfigMap"}, meta.RESTScopeNamespace)
	m.Add(schema.GroupVersionKind{Group: "rbac.authorization.k8s.io", Version: "v1", Kind: "ClusterRoleBinding"}, meta.RESTScopeRoot)
	m.Add(schema.GroupVersionKind{Group: "networking.k8s.io", Version: "v1", Kind: "IngressClass"}, meta.RESTScopeRoot)
	return m
}

func clusterRoleBinding() map[string]any {
	return map[string]any{
		"apiVersion": "rbac.authorization.k8s.io/v1",
		"kind":       "ClusterRoleBinding",
		"metadata":   map[string]any{"name": "escalate"},
	}
}

// A namespaced policy passes its own namespace as the apply() argument, which
// satisfies the namespace-boundary check, but a cluster-scoped resource still
// escapes that namespace. It must be rejected.
func TestGenerateResources_NamespacedPolicyRejectsClusterScoped(t *testing.T) {
	cp := &contextProvider{
		cliEvaluation: true,
		restMapper:    generateTestRESTMapper(),
	}

	err := cp.GenerateResources("tenant-ns", []map[string]any{clusterRoleBinding()})
	assert.Error(t, err, "namespaced policy must not generate a cluster-scoped resource")
	assert.Contains(t, err.Error(), "cross-scope generation denied")
	assert.Empty(t, cp.GetGeneratedResources())
}

// A namespaced resource generated into the policy namespace is still allowed.
func TestGenerateResources_NamespacedPolicyAllowsNamespaced(t *testing.T) {
	cp := &contextProvider{
		cliEvaluation: true,
		restMapper:    generateTestRESTMapper(),
	}

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err := cp.GenerateResources("tenant-ns", []map[string]any{cm})
	assert.NoError(t, err)
	assert.Len(t, cp.GetGeneratedResources(), 1)
	assert.Equal(t, "tenant-ns", cp.GetGeneratedResources()[0].GetNamespace())
}

// A cluster-scoped policy uses an empty namespace argument and may still
// generate cluster-scoped resources.
func TestGenerateResources_ClusterPolicyAllowsClusterScoped(t *testing.T) {
	cp := &contextProvider{
		cliEvaluation: true,
		restMapper:    generateTestRESTMapper(),
	}

	err := cp.GenerateResources("", []map[string]any{clusterRoleBinding()})
	assert.NoError(t, err)
	assert.Len(t, cp.GetGeneratedResources(), 1)
	assert.Empty(t, cp.GetGeneratedResources()[0].GetNamespace())
}

// Regression test for kyverno/kyverno#15722: when the target resource was
// already generated by an earlier UR (e.g. a resync, a retry, or a
// cacheRestore pass), GenerateResources must still report it via
// GetGeneratedResources(). Callers such as WatchManager.SyncWatchers use an
// empty generated-resources list to mean "this policy no longer generates
// anything" and tear down the corresponding watcher/downstream resource. If
// an already-existing resource were silently dropped here, a concurrent UR
// for the same policy (created for a different trigger) would race in and
// delete a resource another UR had just legitimately created.
func TestGenerateResources_ExistingResourceReportedAsGenerated(t *testing.T) {
	existing := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "data",
				"namespace": "tenant-ns",
				"labels": map[string]any{
					kyverno.LabelAppManagedBy:      kyverno.ValueKyvernoApp,
					common.GeneratePolicyLabel:     "test-gpol",
					common.GenerateTriggerUIDLabel: "trigger-uid",
				},
			},
		},
	}
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	require.Len(t, cp.GetGeneratedResources(), 1)
	assert.Equal(t, "data", cp.GetGeneratedResources()[0].GetName())
	assert.Equal(t, "tenant-ns", cp.GetGeneratedResources()[0].GetNamespace())
}

// Two different triggers of the same policy must not "adopt" each other's
// downstream resource just because they happen to render the same target
// name/namespace: the existing resource's trigger-UID label has to match the
// trigger currently being processed, not merely the policy name.
func TestGenerateResources_DifferentTriggerExistingResourceNotAdopted(t *testing.T) {
	existing := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "data",
				"namespace": "tenant-ns",
				"labels": map[string]any{
					kyverno.LabelAppManagedBy:      kyverno.ValueKyvernoApp,
					common.GeneratePolicyLabel:     "test-gpol",
					common.GenerateTriggerUIDLabel: "other-trigger-uid",
				},
			},
		},
	}
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	assert.Empty(t, cp.GetGeneratedResources(), "a resource generated for a different trigger of the same policy must not be adopted")
}

// An existing resource that merely shares the same GVK/namespace/name but is
// NOT labeled as managed by this policy (e.g. an unrelated, user-created
// resource) must never be reported as generated -- otherwise it would be
// silently adopted by the policy and become subject to synchronize/delete
// behavior it was never meant to have.
func TestGenerateResources_UnmanagedExistingResourceNotAdopted(t *testing.T) {
	unrelated := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "data",
				"namespace": "tenant-ns",
				// no Kyverno management labels: this is a pre-existing,
				// user-owned resource that just happens to match.
			},
		},
	}
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, unrelated)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", false)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	assert.Empty(t, cp.GetGeneratedResources(), "an unmanaged pre-existing resource must not be adopted")
}

// Companion case: restoreCache mode must not create the resource, but if it
// already exists it still needs to be reported so the watch manager's cache
// gets restored (the original purpose of cacheRestore, see
// kyverno/kyverno#13571).
func TestGenerateResources_RestoreCacheReportsExistingButDoesNotCreate(t *testing.T) {
	existing := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]any{
				"name":      "data",
				"namespace": "tenant-ns",
				"labels": map[string]any{
					kyverno.LabelAppManagedBy:      kyverno.ValueKyvernoApp,
					common.GeneratePolicyLabel:     "test-gpol",
					common.GenerateTriggerUIDLabel: "trigger-uid",
				},
			},
		},
	}
	fakeClient, err := dclient.NewFakeClient(runtime.NewScheme(), nil, existing)
	require.NoError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	cp := &contextProvider{
		client:     fakeClient,
		restMapper: generateTestRESTMapper(),
	}
	cp.SetGenerateContext("test-gpol", "trigger", "tenant-ns", "v1", "", "Namespace", "trigger-uid", true)

	cm := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "data", "namespace": "tenant-ns"},
	}
	err = cp.GenerateResources("tenant-ns", []map[string]any{cm})
	require.NoError(t, err)
	require.Len(t, cp.GetGeneratedResources(), 1)
	assert.Equal(t, "data", cp.GetGeneratedResources()[0].GetName())

	notYetCreated := map[string]any{
		"apiVersion": "v1",
		"kind":       "ConfigMap",
		"metadata":   map[string]any{"name": "not-yet-created", "namespace": "tenant-ns"},
	}
	cp.ClearGeneratedResources()
	err = cp.GenerateResources("tenant-ns", []map[string]any{notYetCreated})
	require.NoError(t, err)
	assert.Empty(t, cp.GetGeneratedResources(), "restoreCache must not create resources that don't exist yet")
	_, err = fakeClient.GetResource(t.Context(), "v1", "ConfigMap", "tenant-ns", "not-yet-created")
	assert.Error(t, err, "restoreCache must not create resources that don't exist yet")
}

func TestContextProvider_CloneIsolatesPerEvaluationState(t *testing.T) {
	original := &contextProvider{
		generatedResources: []*unstructured.Unstructured{
			{Object: map[string]any{"apiVersion": "v1", "kind": "ConfigMap", "metadata": map[string]any{"name": "orig"}}},
		},
	}
	original.SetGenerateContext("policy-a", "trigger-a", "default", "v1", "", "Pod", "uid-a", true)

	cloned := original.Clone()
	clone, ok := cloned.(*contextProvider)
	require.True(t, ok)

	// Clone is for per-worker execution; it must start with isolated mutable state.
	assert.Empty(t, clone.generatedResources)
	assert.Equal(t, original.genCtx, clone.genCtx)

	clone.SetGenerateContext("policy-b", "trigger-b", "kube-system", "v1", "", "Service", "uid-b", false)
	clone.generatedResources = append(clone.generatedResources, &unstructured.Unstructured{
		Object: map[string]any{"apiVersion": "v1", "kind": "ConfigMap", "metadata": map[string]any{"name": "clone"}},
	})

	assert.Equal(t, "policy-a", original.genCtx.policyName)
	assert.True(t, original.genCtx.restoreCache)
	require.Len(t, original.generatedResources, 1)
	assert.Equal(t, "orig", original.generatedResources[0].GetName())
}
