/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CTLogApplyConfiguration represents an declarative configuration of the CTLog type for use
// with apply.
type CTLogApplyConfiguration struct {
	URL                *string `json:"url,omitempty"`
	RekorPubKey        *string `json:"rekorPubKey,omitempty"`
	CTLogPubKey        *string `json:"ctLogPubKey,omitempty"`
	InsecureIgnoreTlog *bool   `json:"insecureIgnoreTlog,omitempty"`
	InsecureIgnoreSCT  *bool   `json:"insecureIgnoreSCT,omitempty"`
}

// CTLogApplyConfiguration constructs an declarative configuration of the CTLog type for use with
// apply.
func CTLog() *CTLogApplyConfiguration {
	return &CTLogApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *CTLogApplyConfiguration) WithURL(value string) *CTLogApplyConfiguration {
	b.URL = &value
	return b
}

// WithRekorPubKey sets the RekorPubKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RekorPubKey field is set to the value of the last call.
func (b *CTLogApplyConfiguration) WithRekorPubKey(value string) *CTLogApplyConfiguration {
	b.RekorPubKey = &value
	return b
}

// WithCTLogPubKey sets the CTLogPubKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CTLogPubKey field is set to the value of the last call.
func (b *CTLogApplyConfiguration) WithCTLogPubKey(value string) *CTLogApplyConfiguration {
	b.CTLogPubKey = &value
	return b
}

// WithInsecureIgnoreTlog sets the InsecureIgnoreTlog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InsecureIgnoreTlog field is set to the value of the last call.
func (b *CTLogApplyConfiguration) WithInsecureIgnoreTlog(value bool) *CTLogApplyConfiguration {
	b.InsecureIgnoreTlog = &value
	return b
}

// WithInsecureIgnoreSCT sets the InsecureIgnoreSCT field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InsecureIgnoreSCT field is set to the value of the last call.
func (b *CTLogApplyConfiguration) WithInsecureIgnoreSCT(value bool) *CTLogApplyConfiguration {
	b.InsecureIgnoreSCT = &value
	return b
}
