/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// SourceApplyConfiguration represents an declarative configuration of the Source type for use
// with apply.
type SourceApplyConfiguration struct {
	Repository           *string                   `json:"repository,omitempty"`
	SignaturePullSecrets []v1.LocalObjectReference `json:"PullSecrets,omitempty"`
	TagPrefix            *string                   `json:"tagPrefix,omitempty"`
}

// SourceApplyConfiguration constructs an declarative configuration of the Source type for use with
// apply.
func Source() *SourceApplyConfiguration {
	return &SourceApplyConfiguration{}
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *SourceApplyConfiguration) WithRepository(value string) *SourceApplyConfiguration {
	b.Repository = &value
	return b
}

// WithSignaturePullSecrets adds the given value to the SignaturePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SignaturePullSecrets field.
func (b *SourceApplyConfiguration) WithSignaturePullSecrets(values ...v1.LocalObjectReference) *SourceApplyConfiguration {
	for i := range values {
		b.SignaturePullSecrets = append(b.SignaturePullSecrets, values[i])
	}
	return b
}

// WithTagPrefix sets the TagPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TagPrefix field is set to the value of the last call.
func (b *SourceApplyConfiguration) WithTagPrefix(value string) *SourceApplyConfiguration {
	b.TagPrefix = &value
	return b
}
