package webhook

import (
	"slices"
	"testing"

	policiesv1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	"github.com/kyverno/kyverno/pkg/config"
	engineapi "github.com/kyverno/kyverno/pkg/engine/api"
	"github.com/stretchr/testify/assert"
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func TestBuildWebhookRulesFineGrainedNamespacedImagePolicyAutogen(t *testing.T) {
	policy := &policiesv1beta1.NamespacedImageValidatingPolicy{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "verify-images",
			Namespace: "team-a",
		},
		Spec: policiesv1beta1.ImageValidatingPolicySpec{
			MatchConstraints: &admissionregistrationv1.MatchResources{
				ResourceRules: []admissionregistrationv1.NamedRuleWithOperations{{
					RuleWithOperations: admissionregistrationv1.RuleWithOperations{
						Operations: []admissionregistrationv1.OperationType{admissionregistrationv1.Create},
						Rule: admissionregistrationv1.Rule{
							APIGroups:   []string{""},
							APIVersions: []string{"v1"},
							Resources:   []string{"pods"},
						},
					},
				}},
			},
			MatchConditions: []admissionregistrationv1.MatchCondition{{
				Name:       "always",
				Expression: "true",
			}},
		},
	}
	cache := NewExpressionCache()
	cache.AddPolicyExpressions(policy.GetMatchConditions())

	webhooks := buildWebhookRules(
		config.NewDefaultConfiguration(false),
		"",
		config.NamespacedImageValidatingPolicyValidateWebhookName,
		"/nivpol/validate",
		0,
		nil,
		[]engineapi.GenericPolicy{engineapi.NewNamespacedImageValidatingPolicy(policy)},
		cache,
	)

	if !assert.Len(t, webhooks, 1) {
		return
	}
	var hasDeploymentRule bool
	for _, rule := range webhooks[0].Rules {
		if slices.Contains(rule.APIGroups, "apps") && slices.Contains(rule.Resources, "deployments") {
			hasDeploymentRule = true
			break
		}
	}
	assert.True(t, hasDeploymentRule, "expected an autogenerated Deployment webhook rule")
}
