{{- range $name, $values := .Values.additionalPolicyExceptions }}
{{- if not (has $values.kind (list "PolicyException")) }}
{{- fail (printf "Invalid kind (%s) for policy named %s." $values.kind $name) }}
{{- end }}
apiVersion: policies.kyverno.io/v1
kind: {{ default $values.kind "PolicyException" }}
metadata:
  name: {{ $name }}
    {{- if $values.namespace  }}
  namespace: {{ $values.namespace | default "kyverno" }}
  annotations: {{- toYaml (default dict $values.annotations) | nindent 4 }}
  labels: {{- include "kyverno-policies.labels" $ | nindent 4 }}
spec: {{- toYaml $values.spec | nindent 2 }}
{{- end }}