{{- /* Normalize customPolicies to a list, easier to loop over */ -}}
{{- $customPolicies := .Values.customPolicies | default (list) -}}

{{- if kindIs "map" $customPolicies -}}
  {{- $customPolicies = values $customPolicies -}}
{{- end -}}

{{- range $customPolicies }}
---
  {{- if kindIs "map" . }}
  {{- tpl (toYaml .) $ | nindent 0 }}
  {{- else if kindIs "string" . }}
  {{- tpl . $ | nindent 0 }}
  {{- end }}
{{- end }}
