package policy

import (
	"context"

	policiesv1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	"github.com/kyverno/kyverno/pkg/background/common"
	generateutils "github.com/kyverno/kyverno/pkg/background/generate"
	engineapi "github.com/kyverno/kyverno/pkg/engine/api"
	matchutils "github.com/kyverno/kyverno/pkg/utils/match"
	"go.uber.org/multierr"
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/sets"
)

func (pc *policyController) createURForGeneratingPolicy(gpol *policiesv1beta1.GeneratingPolicy) error {
	ur := newGenerateUR(engineapi.NewGeneratingPolicy(gpol))
	// get the downstream resources that are generated by the gpol
	downstreams := pc.watchManager.GetDownstreams(gpol.GetName())
	if len(downstreams) == 0 {
		// create a UR to restore the dynamic watcher cache in case backgound controller is restarted
		pc.log.V(4).Info("no downstream resources found for generating policy, creating UR to restore dynamic watcher cache")
		triggers := pc.getGpolTriggers(gpol.Spec.MatchConstraints)
		for _, trigger := range triggers {
			addRuleContext(ur, gpol.GetName(), common.ResourceSpecFromUnstructured(*trigger), false, true)
		}
	} else {
		// sync the gpol changes to the downstream resources
		pc.log.V(4).Info("sync gpol changes to downstream targets")
		for _, downstream := range downstreams {
			labels := downstream.GetLabels()
			// fetch the trigger resource labels from the downstream resource to build the UR
			trigger := generateutils.TriggerFromLabels(labels)
			addRuleContext(ur, gpol.GetName(), trigger, false, false)
		}
		// delete the downstream resources that are generated by the gpol
		pc.watchManager.DeleteDownstreams(gpol.GetName(), nil)
	}
	if len(ur.Spec.RuleContext) == 0 {
		return nil
	}
	pc.log.V(4).Info("creating URs for GeneratingPolicy", "total", len(ur.Spec.RuleContext))
	var errs []error
	for _, batch := range splitUR(ur, generateBatchSize) {
		if err := pc.submitUR(context.TODO(), batch); err != nil {
			errs = append(errs, err)
		}
	}
	return multierr.Combine(errs...)
}

func (pc *policyController) handleGenerateExisting(gpol *policiesv1beta1.GeneratingPolicy) error {
	ur := newGenerateUR(engineapi.NewGeneratingPolicy(gpol))
	triggers := pc.getGpolTriggers(gpol.Spec.MatchConstraints)
	for _, trigger := range triggers {
		addRuleContext(ur, gpol.GetName(), common.ResourceSpecFromUnstructured(*trigger), false, false)
	}
	if len(ur.Spec.RuleContext) == 0 {
		return nil
	}
	pc.log.V(4).Info("creating URs for GeneratingPolicy generateExisting", "total", len(ur.Spec.RuleContext))
	var errs []error
	for _, batch := range splitUR(ur, generateBatchSize) {
		if err := pc.submitUR(context.TODO(), batch); err != nil {
			errs = append(errs, err)
		}
	}
	return multierr.Combine(errs...)
}

func (pc *policyController) createURForNamespacedGeneratingPolicy(ngpol *policiesv1beta1.NamespacedGeneratingPolicy) error {
	ur := newGenerateUR(engineapi.NewNamespacedGeneratingPolicy(ngpol))
	policyKey := ngpol.GetNamespace() + "/" + ngpol.GetName()
	// get the downstream resources that are generated by the ngpol
	downstreams := pc.watchManager.GetDownstreams(policyKey)
	if len(downstreams) == 0 {
		// create a UR to restore the dynamic watcher cache in case background controller is restarted
		pc.log.V(4).Info("no downstream resources found for namespaced generating policy, creating UR to restore dynamic watcher cache")
		triggers := filterTriggersByNamespace(pc.getGpolTriggers(ngpol.Spec.MatchConstraints), ngpol.GetNamespace())
		for _, trigger := range triggers {
			addRuleContext(ur, policyKey, common.ResourceSpecFromUnstructured(*trigger), false, true)
		}
	} else {
		// sync the ngpol changes to the downstream resources
		pc.log.V(4).Info("sync ngpol changes to downstream targets")
		for _, downstream := range downstreams {
			labels := downstream.GetLabels()
			// fetch the trigger resource labels from the downstream resource to build the UR
			trigger := generateutils.TriggerFromLabels(labels)
			addRuleContext(ur, policyKey, trigger, false, false)
		}
		// delete the downstream resources that are generated by the ngpol
		pc.watchManager.DeleteDownstreams(policyKey, nil)
	}
	if len(ur.Spec.RuleContext) == 0 {
		return nil
	}
	pc.log.V(4).Info("creating URs for NamespacedGeneratingPolicy", "total", len(ur.Spec.RuleContext))
	var errs []error
	for _, batch := range splitUR(ur, generateBatchSize) {
		if err := pc.submitUR(context.TODO(), batch); err != nil {
			errs = append(errs, err)
		}
	}
	return multierr.Combine(errs...)
}

func (pc *policyController) handleNamespacedGenerateExisting(ngpol *policiesv1beta1.NamespacedGeneratingPolicy) error {
	ur := newGenerateUR(engineapi.NewNamespacedGeneratingPolicy(ngpol))
	policyKey := ngpol.GetNamespace() + "/" + ngpol.GetName()
	triggers := filterTriggersByNamespace(pc.getGpolTriggers(ngpol.Spec.MatchConstraints), ngpol.GetNamespace())
	for _, trigger := range triggers {
		addRuleContext(ur, policyKey, common.ResourceSpecFromUnstructured(*trigger), false, false)
	}
	if len(ur.Spec.RuleContext) == 0 {
		return nil
	}
	pc.log.V(4).Info("creating URs for NamespacedGeneratingPolicy generateExisting", "total", len(ur.Spec.RuleContext))
	var errs []error
	for _, batch := range splitUR(ur, generateBatchSize) {
		if err := pc.submitUR(context.TODO(), batch); err != nil {
			errs = append(errs, err)
		}
	}
	return multierr.Combine(errs...)
}

func (pc *policyController) getGpolTriggers(match *admissionregistrationv1.MatchResources) []*unstructured.Unstructured {
	var triggers []*unstructured.Unstructured
	objectSelector := match.ObjectSelector
	nsSelector := match.NamespaceSelector

	for _, rule := range match.ResourceRules {
		for _, group := range rule.APIGroups {
			for _, resource := range rule.Resources {
				versions := rule.APIVersions
				// RESTMapper does not support wildcard versions. Resolve all
				// concrete versions for the given group/resource before processing.
				if len(rule.APIVersions) == 1 && rule.APIVersions[0] == "*" {
					gvks, err := pc.restMapper.KindsFor(
						schema.GroupVersionResource{
							Group:    group,
							Resource: resource,
						},
					)
					if err != nil {
						pc.log.Error(err, "failed to resolve wildcard APIVersions", "group", group, "resource", resource)
						continue
					}
					versionSet := sets.New[string]()
					for _, gvk := range gvks {
						versionSet.Insert(gvk.Version)
					}
					versions = sets.List(versionSet)
				}
				for _, version := range versions {
					groupVersion := schema.GroupVersion{
						Group:   group,
						Version: version,
					}
					gvr := schema.GroupVersionResource{Group: group, Version: version, Resource: resource}
					gvk, err := pc.restMapper.KindFor(gvr)
					if err != nil {
						pc.log.Error(err, "mapping gvr to gvk failed", "gvr", gvr)
						continue
					}
					resources, err := pc.client.ListResource(context.TODO(), groupVersion.String(), gvk.Kind, "", objectSelector)
					if err != nil {
						pc.log.Error(err, "failed to list resources", "groupVersion", groupVersion, "kind", gvk.Kind)
						continue
					}
					for i, res := range resources.Items {
						if !pc.triggerMatches(res, gvr, rule.ResourceNames, match.ExcludeResourceRules, nsSelector) {
							continue
						}
						triggers = append(triggers, &resources.Items[i])
					}
				}
			}
		}
	}
	return triggers
}

func filterTriggersByNamespace(triggers []*unstructured.Unstructured, namespace string) []*unstructured.Unstructured {
	if namespace == "" {
		return triggers
	}
	filtered := make([]*unstructured.Unstructured, 0, len(triggers))
	for _, trigger := range triggers {
		if trigger.GetNamespace() == namespace || (trigger.GetKind() == "Namespace" && trigger.GetName() == namespace) {
			filtered = append(filtered, trigger)
		}
	}
	return filtered
}

func (pc *policyController) triggerMatches(
	resource unstructured.Unstructured,
	gvr schema.GroupVersionResource,
	resourceNames []string,
	excludeRules []admissionregistrationv1.NamedRuleWithOperations,
	nsSelector *metav1.LabelSelector,
) bool {
	// check if the resource matches the excluded rules
	if len(excludeRules) > 0 {
		for _, rule := range excludeRules {
			if contains(rule.APIGroups, gvr.Group) &&
				contains(rule.APIVersions, gvr.Version) &&
				contains(rule.Resources, gvr.Resource) &&
				(len(rule.ResourceNames) == 0 || contains(rule.ResourceNames, resource.GetName())) {
				return false
			}
		}
	}

	// check if the resource matches the names specified in the rule
	if len(resourceNames) > 0 {
		if !contains(resourceNames, resource.GetName()) {
			return false
		}
	}

	// check if the resource's namespace matches the namespace selector
	if nsSelector != nil {
		var labels map[string]string
		var nsName string
		// for namespace resources, check the labels directly
		if resource.GetKind() == "Namespace" {
			labels = resource.GetLabels()
			nsName = resource.GetName()
		} else {
			nsName := resource.GetNamespace()
			namespace, err := pc.client.GetResource(context.TODO(), "v1", "Namespace", "", nsName)
			if err != nil {
				pc.log.Error(err, "failed to get namespace", "name", nsName)
				return false
			}
			labels = namespace.GetLabels()
		}
		// check if the namespace labels match the namespace selector
		isMatch, err := matchutils.CheckSelector(nsSelector, labels)
		if err != nil {
			pc.log.Error(err, "failed to check namespace selector", "namespace", nsName)
			return false
		}
		if !isMatch {
			return false
		}
	}
	return true
}
