package engine

import (
	"context"
	"sync"

	policiesv1beta1 "github.com/kyverno/api/api/policies.kyverno.io/v1beta1"
	"github.com/kyverno/kyverno/pkg/cel/engine"
	"github.com/kyverno/kyverno/pkg/cel/matching"
	"github.com/kyverno/kyverno/pkg/cel/policies/mpol/autogen"
	"github.com/kyverno/kyverno/pkg/cel/policies/mpol/compiler"
	policiesv1beta1listers "github.com/kyverno/kyverno/pkg/client/listers/policies.kyverno.io/v1beta1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apiserver/pkg/admission"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type reconciler struct {
	client       client.Client
	compiler     compiler.Compiler
	lock         *sync.RWMutex
	policies     map[string][]Policy
	polexLister  policiesv1beta1listers.PolicyExceptionLister
	polexEnabled bool
}

func newReconciler(
	client client.Client,
	compiler compiler.Compiler,
	polexLister policiesv1beta1listers.PolicyExceptionLister,
	polexEnabled bool,
) *reconciler {
	return &reconciler{
		client:       client,
		compiler:     compiler,
		lock:         &sync.RWMutex{},
		policies:     map[string][]Policy{},
		polexLister:  polexLister,
		polexEnabled: polexEnabled,
	}
}

func (r *reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	var policy policiesv1beta1.MutatingPolicyLike
	mpol := &policiesv1beta1.MutatingPolicy{}
	err := r.client.Get(ctx, req.NamespacedName, mpol)
	if err == nil {
		policy = mpol
	} else if errors.IsNotFound(err) {
		// Try NamespacedMutatingPolicy
		nmpol := &policiesv1beta1.NamespacedMutatingPolicy{}
		err = r.client.Get(ctx, req.NamespacedName, nmpol)
		if err == nil {
			policy = nmpol
		} else if errors.IsNotFound(err) {
			r.lock.Lock()
			delete(r.policies, req.NamespacedName.String())
			r.lock.Unlock()
			return ctrl.Result{}, nil
		} else {
			return ctrl.Result{}, err
		}
	} else {
		return ctrl.Result{}, err
	}

	if policy.GetStatus().Generated {
		r.lock.Lock()
		delete(r.policies, req.NamespacedName.String())
		r.lock.Unlock()
		return ctrl.Result{}, nil
	}

	var exceptions []*policiesv1beta1.PolicyException
	if r.polexEnabled {
		exceptions, err = engine.ListExceptions(r.polexLister, policy.GetKind(), policy.GetName())
		if err != nil {
			return ctrl.Result{}, err
		}
	}
	compiled, errs := r.compiler.Compile(policy, exceptions)
	if len(errs) > 0 {
		return ctrl.Result{}, errs[0]
	}
	policies := []Policy{{
		Policy:         policy,
		CompiledPolicy: compiled,
	}}

	generated, err := autogen.Autogen(policy)
	if err != nil {
		return ctrl.Result{}, err
	}
	for _, gen := range generated {
		// Create a copy of the policy with autogenerated spec
		autogenPolicy := policy.DeepCopyObject().(policiesv1beta1.MutatingPolicyLike)
		*autogenPolicy.GetSpec() = *gen.Spec

		compiled, errs := r.compiler.Compile(autogenPolicy, exceptions)
		if len(errs) > 0 {
			return ctrl.Result{}, errs[0]
		}
		policies = append(policies, Policy{
			Policy:         autogenPolicy,
			CompiledPolicy: compiled,
		})
	}

	r.lock.Lock()
	r.policies[req.NamespacedName.String()] = policies
	r.lock.Unlock()
	return ctrl.Result{}, nil
}

func (r *reconciler) Fetch(ctx context.Context, mutateExisting bool) []Policy {
	r.lock.RLock()
	defer r.lock.RUnlock()
	var policies []Policy
	if !mutateExisting {
		for _, p := range r.policies {
			policies = append(policies, p...)
		}
		return policies
	}

	for _, p := range r.policies {
		for _, mpol := range p {
			if mpol.Policy.GetSpec().MutateExistingEnabled() {
				policies = append(policies, mpol)
			}
		}
	}
	return policies
}

func (r *reconciler) MatchesMutateExisting(ctx context.Context, attr admission.Attributes, namespace *corev1.Namespace) []string {
	policies := r.Fetch(ctx, true)
	matchedPolicies := []string{}
	for _, mpol := range policies {
		if !Or(ClusteredPolicy(), NamespacedPolicy(attr.GetNamespace()))(mpol.Policy) {
			continue
		}

		matcher := matching.NewMatcher()
		matchConstraints := mpol.Policy.GetSpec().MatchConstraints
		if ok, err := matcher.Match(&matching.MatchCriteria{Constraints: matchConstraints}, attr, namespace); err != nil || !ok {
			continue
		}
		if mpol.Policy.GetSpec().MatchConditions != nil {
			if !mpol.CompiledPolicy.MatchesConditions(ctx, attr, namespace) {
				continue
			}
		}
		matchedPolicies = append(matchedPolicies, mpol.Policy.GetName())
	}
	return matchedPolicies
}
