# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Caching

permissions: {}

on:
  push:
    branches:
      - main

jobs:
  gomod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/go/setup
        with:
          gomod-cache-prefix: '' # disable gomod cache
          gobuild-cache-prefix: '' # disable gobuild cache
      - name: Download modules
        shell: bash
        run: |
          set -e
          go mod download && go mod tidy
          (cd hack/controller-gen && go mod download && go mod tidy)
          (cd hack/api-group-resources && go mod download && go mod tidy)
          make install-tools
      - name: Save gomod cache
        uses: ./.github/actions/go/save-cache
        with:
          path: ${{ steps.setup-go.outputs.gomod-cache }}
          cache-prefix: gomod

  gobuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/go/setup
        with:
          gobuild-cache-prefix: '' # disable gobuild cache
      - name: Install Ko
        uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9
      - name: Build all
        shell: bash
        run: |
          set -e
          KO=/usr/local/bin/ko VERSION=${{ github.ref_name }} make image-build-all build-all
      - name: Save gobuild cache
        uses: ./.github/actions/go/save-cache
        with:
          path: ${{ steps.setup-go.outputs.gobuild-cache }}
          cache-prefix: gobuild
