# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Go imports

permissions: {}

on:
  pull_request:
    branches:
      - main
      - release-*
  push:
    branches:
      - main
      - release-*

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    name: Check imports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: ./.github/actions/go/setup
      - name: goimports check
        run: make imports-check

  issue-sync:
    needs:
      - check
    if: always() && github.event_name == 'push'
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Sync issue
        uses: ./.github/actions/workflow/failure-issue
