# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Actions

permissions: {}

on:
  pull_request:
    branches:
      - main
      - release-*
  push:
    branches:
      - main
      - release-*

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    name: Ensure SHA pinned actions
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@cc9ffdc62fadb9f83b46dd0979d9ad50408cc6a6 # v5.0.2
        with:
          # slsa-github-generator requires using a semver tag for reusable workflows.
          # See: https://github.com/slsa-framework/slsa-github-generator#referencing-slsa-builders-and-generators
          allowlist: |
            slsa-framework/slsa-github-generator

  sync-issue:
    if: always() && github.event_name == 'push'
    needs:
      - check
    permissions:
      issues: write
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Sync issue
        uses: ./.github/actions/workflow/failure-issue
