# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Go

permissions: {}

on:
  pull_request:
    branches:
      - main
      - release-*
  push:
    branches:
      - main
      - release-*

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: ./.github/actions/go/setup
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.6.0
          skip-cache: true

  issue-sync:
    needs:
      - check
    if: always() && github.event_name == 'push'
    runs-on: ubuntu-slim
    steps:
      - name: Sync issue
        uses: ./.github/actions/workflow/failure-issue
