# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Issue and PR comment commands

permissions: {}

on:
  issue_comment:
    types: 
      - created
      - edited

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: jpmcb/prow-github-actions@c44ac3a57d67639e39e4a4988b52049ef45b80dd # v2.0.0
        with:
          prow-commands: '/assign 
            /unassign
            /lgtm 
            /milestone'
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  # /cherry-pick command, only send a message if PR is unmerged, cherry-pick if PR was already merged
  cherry-pick:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/cherry-pick')
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
    # TODO(lucchmielowski): Fix slash in command name issue and reactivate for finer-grained controls
    # - name: Check for Command
    #    id: command
    #    uses: xt0rted/slash-command-action@v2
    #   continue-on-error: true
    #   with:
    #     command: cherry-pick
    #     reaction: "true"
    #     reaction-type: "+1"
    #     allow-edits: "false"
    #     permission-level: write
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}

      # NOTE: can be removed if slash-command-action is uncommented
      - name: React to comment
        uses: dkershner6/reaction-action@97ede302a1b145b3739dec3ca84a489a34ef48b5 # v2.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reaction: "+1"

      - name: Check if PR is merged
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: check-merged
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return {
              merged: pr.data.merged,
              state: pr.data.state,
              mergeCommit: pr.data.merge_commit_sha
            };

      - name: Extract target branch
        if: fromJSON(steps.check-merged.outputs.result).merged == true
        id: extract-branch
        run: echo "branch=$(echo '${{ github.event.comment.body }}' | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: comment pr unmerged
        if: ${{ fromJSON(steps.check-merged.outputs.result).merged == false && fromJSON(steps.check-merged.outputs.result).state != 'closed' }}
        uses: ben-z/actions-comment-on-issue@402eb412a8f396be0d4ac52a823ec7121206cc26 # v1.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Commits from this PR will automatically be cherry-picked once this PR gets merged.

      - name: Checkout repository
        if: fromJSON(steps.check-merged.outputs.result).merged == true
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Cherry Pick
        if: fromJSON(steps.check-merged.outputs.result).merged == true
        uses: ./.github/actions/cherry-pick
        continue-on-error: true # Send failure comment to PR
        id: cherry-pick
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source-pr: ${{ github.event.issue.number }}
          source-pr-title: ${{ github.event.issue.title }}
          target-branches: ${{ steps.extract-branch.outputs.branch }}
          merge-commit: ${{ fromJson(steps.check-merged.outputs.result).mergeCommit }}

      - name: comment cherry-pick fail
        if: ${{ steps.cherry-pick.outputs.success == false && fromJSON(steps.check-merged.outputs.result).merged == true }}
        uses: ben-z/actions-comment-on-issue@402eb412a8f396be0d4ac52a823ec7121206cc26 # v1.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |            
            :no_entry_sign: Cherry picking merge commit `${{ fromJSON(steps.check-merged.outputs.result).mergeCommit}}` failed. 
            
            Please check workflow logs.
            
