# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Prow

permissions: {}

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  assign:
    name: Prow Assign
    # Non-members can self-assign issues labeled 'good first issue' only.
    # Org members, owners, and collaborators can (un)assign anywhere.
    if: |
      contains(fromJson('["MEMBER", "OWNER", "COLLABORATOR"]'), github.event.comment.author_association) ||
      contains(github.event.issue.labels.*.name, 'good first issue')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: jpmcb/prow-github-actions@187c5e3cd95a329c43448e1bdb3b1f5249232e44 # v3.0.1
        with:
          prow-commands: "/assign
            /unassign"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  execute:
    name: Prow
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: jpmcb/prow-github-actions@187c5e3cd95a329c43448e1bdb3b1f5249232e44 # v3.0.1
        with:
          prow-commands: "/lgtm
            /milestone"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
