# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: DCO

permissions: {}

on:
  pull_request:
    branches:
      - main
      - release-*
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dco:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check DCO sign-off on all PR commits
        uses: tisonkun/actions-dco@f1024cd563550b5632e754df11b7d30b73be54a5 # v1.1
