# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Dev container

permissions: {}

on:
  pull_request:
    branches:
      - main
      - release-*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build devcontainer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check for .devcontainer changes
        id: changed-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: .devcontainer/**
      - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          android: true
          docker-images: false
          dotnet: false
          haskell: false
          large-packages: false
          swap-storage: false
          tool-cache: false
      - name: Build devcontainer image
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3
        with:
          push: never
