# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build images

permissions: {}

on:
  pull_request:
    branches:
      - main
      - release-*
  merge_group:
    types: [checks_requested]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: ./.github/actions/go/setup
      - name: Install Ko
        uses: ./.github/actions/tools/ko
      - name: ko build
        shell: bash
        run: |
          set -e
          VERSION=${{ github.ref_name }} make ko-build-all
      - name: Trivy Scan Image
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: fs
          scan-ref: '.'
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          cache: false
        env:
          TRIVY_DB_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-db:2'
