name: K6

permissions: {}

on:
  push: {}

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: ./.github/actions/go/setup
      - name: Install helm
        uses: ./.github/actions/tools/helm
      - name: Install kind
        uses: ./.github/actions/tools/kind
      - name: Install k6
        uses: ./.github/actions/tools/k6
      - name: Create cluster
        uses: ./.github/actions/perf-test/cluster
      - name: Create test namespace
        shell: bash
        run: kubectl create ns testns
      - name: Expose prometheus
        shell: bash
        run: kubectl port-forward -n monitoring svc/kube-prometheus-stack-prometheus 9090:9090 &
      - name: Run test
        shell: bash
        run: |
          K6_WEB_DASHBOARD_PERIOD=5s \
          K6_WEB_DASHBOARD_EXPORT=k6.html \
          K6_PROMETHEUS_RW_TREND_STATS="avg,min,med,max,p(90),p(95),p(99)" \
          k6 run \
            --vus 100 --iterations 1000 \
            --no-connection-reuse \
            --no-vu-connection-reuse \
            --no-usage-report \
            --quiet \
            --summary-mode full --summary-export k6-summary.json --summary-trend-stats "avg,min,med,max,p(90),p(95),p(99)" \
            --new-machine-readable-summary \
            --out web-dashboard \
            --out experimental-prometheus-rw=http://localhost:9090/api/v1/write \
            --out json=k6.json \
            ./scratch/k6/script.js
      - name: Collect summary
        shell: bash
        run: ./scripts/k6-summary-to-markdown.sh >> $GITHUB_STEP_SUMMARY

  kyverno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: ./.github/actions/go/setup
      - name: Install tools
        uses: ./.github/actions/tools/install
        with:
          k6: true
          helm: true
          kind: true
          ko: true
      - name: K6
        shell: bash
        run: |
          set -e

          # create cluster
          make kind-create-cluster

          # install prometheus
          helm upgrade --install --wait --timeout 15m \
            --namespace monitoring --create-namespace \
            --repo https://prometheus-community.github.io/helm-charts \
            kube-prometheus-stack kube-prometheus-stack --values - <<EOF
          prometheus:
            prometheusSpec:
              enableRemoteWriteReceiver: true
              serviceMonitorSelectorNilUsesHelmValues: false
          kubeEtcd:
            service:
              targetPort: 2382
          EOF

          # install kwok
          kubectl apply -f "https://github.com/kubernetes-sigs/kwok/releases/download/v0.7.0/kwok.yaml"
          kubectl apply -f "https://github.com/kubernetes-sigs/kwok/releases/download/v0.7.0/stage-fast.yaml"
          kubectl apply -f "https://github.com/kubernetes-sigs/kwok/releases/download/v0.7.0/metrics-usage.yaml"

          # create kwok node
          kubectl create -f - <<EOF
          apiVersion: v1
          kind: Node
          metadata:
            annotations:
              node.alpha.kubernetes.io/ttl: "0"
              kwok.x-k8s.io/node: fake
            labels:
              beta.kubernetes.io/arch: amd64
              beta.kubernetes.io/os: linux
              kubernetes.io/arch: amd64
              kubernetes.io/os: linux
              kubernetes.io/role: agent
              node-role.kubernetes.io/agent: ""
              type: kwok
            generateName: kwok-node-
          spec:
            taints: # Avoid scheduling actual running pods to fake Node
            - effect: NoSchedule
              key: kwok.x-k8s.io/node
              value: fake
          status:
            allocatable:
              cpu: 32
              memory: 256Gi
              pods: 110
            capacity:
              cpu: 32
              memory: 256Gi
              pods: 110
            nodeInfo:
              architecture: amd64
              bootID: ""
              containerRuntimeVersion: ""
              kernelVersion: ""
              kubeProxyVersion: fake
              kubeletVersion: fake
              machineID: ""
              operatingSystem: linux
              osImage: ""
              systemUUID: ""
            phase: Running
          EOF

          # install kyverno
          make kind-deploy-kyverno

          # create test namespace
          kubectl create ns testns

          # expose prometheus
          kubectl port-forward -n monitoring svc/kube-prometheus-stack-prometheus 9090:9090 &

          # run test
          K6_WEB_DASHBOARD_PERIOD=5s \
          K6_WEB_DASHBOARD_EXPORT=k6.html \
          K6_PROMETHEUS_RW_TREND_STATS="avg,min,med,max,p(90),p(95),p(99)" \
          k6 run \
            --vus 100 --iterations 1000 \
            --no-connection-reuse \
            --no-vu-connection-reuse \
            --no-usage-report \
            --quiet \
            --summary-mode full --summary-export k6-summary.json --summary-trend-stats "avg,min,med,max,p(90),p(95),p(99)" \
            --new-machine-readable-summary \
            --out web-dashboard \
            --out experimental-prometheus-rw=http://localhost:9090/api/v1/write \
            --out json=k6.json \
            ./scratch/k6/script.js

          ./scripts/k6-summary-to-markdown.sh >> $GITHUB_STEP_SUMMARY

  kyverno-pss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: ./.github/actions/go/setup
      - name: Install tools
        uses: ./.github/actions/tools/install
        with:
          k6: true
          helm: true
          kind: true
          ko: true
      - name: K6
        shell: bash
        run: |
          set -e

          # create cluster
          make kind-create-cluster

          # install prometheus
          helm upgrade --install --wait --timeout 15m \
            --namespace monitoring --create-namespace \
            --repo https://prometheus-community.github.io/helm-charts \
            kube-prometheus-stack kube-prometheus-stack --values - <<EOF
          prometheus:
            prometheusSpec:
              enableRemoteWriteReceiver: true
              serviceMonitorSelectorNilUsesHelmValues: false
          kubeEtcd:
            service:
              targetPort: 2382
          EOF

          # install kwok
          kubectl apply -f "https://github.com/kubernetes-sigs/kwok/releases/download/v0.7.0/kwok.yaml"
          kubectl apply -f "https://github.com/kubernetes-sigs/kwok/releases/download/v0.7.0/stage-fast.yaml"
          kubectl apply -f "https://github.com/kubernetes-sigs/kwok/releases/download/v0.7.0/metrics-usage.yaml"

          # create kwok node
          kubectl create -f - <<EOF
          apiVersion: v1
          kind: Node
          metadata:
            annotations:
              node.alpha.kubernetes.io/ttl: "0"
              kwok.x-k8s.io/node: fake
            labels:
              beta.kubernetes.io/arch: amd64
              beta.kubernetes.io/os: linux
              kubernetes.io/arch: amd64
              kubernetes.io/os: linux
              kubernetes.io/role: agent
              node-role.kubernetes.io/agent: ""
              type: kwok
            generateName: kwok-node-
          spec:
            taints: # Avoid scheduling actual running pods to fake Node
            - effect: NoSchedule
              key: kwok.x-k8s.io/node
              value: fake
          status:
            allocatable:
              cpu: 32
              memory: 256Gi
              pods: 110
            capacity:
              cpu: 32
              memory: 256Gi
              pods: 110
            nodeInfo:
              architecture: amd64
              bootID: ""
              containerRuntimeVersion: ""
              kernelVersion: ""
              kubeProxyVersion: fake
              kubeletVersion: fake
              machineID: ""
              operatingSystem: linux
              osImage: ""
              systemUUID: ""
            phase: Running
          EOF

          # install kyverno
          make kind-deploy-kyverno

          # install policies
          helm upgrade --install --wait --timeout 15m \
            --namespace kyverno --create-namespace \
            --repo https://kyverno.github.io/kyverno/ \
            kyverno-policies kyverno-policies

          # create test namespace
          kubectl create ns testns

          # expose prometheus
          kubectl port-forward -n monitoring svc/kube-prometheus-stack-prometheus 9090:9090 &

          # run test
          K6_WEB_DASHBOARD_PERIOD=5s \
          K6_WEB_DASHBOARD_EXPORT=k6.html \
          K6_PROMETHEUS_RW_TREND_STATS="avg,min,med,max,p(90),p(95),p(99)" \
          k6 run \
            --vus 100 --iterations 1000 \
            --no-connection-reuse \
            --no-vu-connection-reuse \
            --no-usage-report \
            --quiet \
            --summary-mode full --summary-export k6-summary.json --summary-trend-stats "avg,min,med,max,p(90),p(95),p(99)" \
            --new-machine-readable-summary \
            --out web-dashboard \
            --out experimental-prometheus-rw=http://localhost:9090/api/v1/write \
            --out json=k6.json \
            ./scratch/k6/script.js

          ./scripts/k6-summary-to-markdown.sh >> $GITHUB_STEP_SUMMARY
