# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Nancy

permissions: {}

on:
  workflow_dispatch:
  schedule:
    - cron: '23 2 * * *' # Every day at 02:23 UTC

    


jobs:
  nancy-scan:
    runs-on: ubuntu-latest
    name: nancy-scan
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup build env
        uses: ./.github/actions/setup-build-env
        timeout-minutes: 10
      - name: WriteGoList
        run: go list -json -deps ./... > go.list
      - name: Nancy SAST Scan
        uses: sonatype-nexus-community/nancy-github-action@726e338312e68ecdd4b4195765f174d3b3ce1533 # v1.0.3
        with:
          output_format: json
          output-file: nancy-results.json
      - name: Parse scan results
        id: parse-results
        run: |
          if [ -s nancy-results.json ]; then
            echo "Vulnerabilities found, creating issue"
            echo "results=found" >> $GITHUB_OUTPUT
          else
            echo "No vulnerabilities found, halting"
            echo "results=nothing" >> $GITHUB_OUTPUT
          fi
      - name: Upload vulnerability scan report
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: steps.parse-results.outputs.results == 'found'
        with:
          name: nancy-results.json
          path: nancy-results.json
          if-no-files-found: error

  open-issue:
    runs-on: ubuntu-latest
    if: needs.nancy-scan.result == 'success'
    needs: nancy-scan
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Download scan results
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: nancy-results.json
      - name: Set scan output
        id: set-scan-output
        run: echo "results=$(cat nancy-results.json | jq -c)" >> $GITHUB_OUTPUT
      - uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESULTS: ${{ steps.set-scan-output.outputs.results }}
        with:
          filename: .github/ISSUE_TEMPLATE/VULN-TEMPLATE.md
        