# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: PR update

permissions: {}

on:
  push:
    branches:
      - main
      - release-*

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    env:
      PR_UPDATE_TOKEN: ${{ secrets.PR_UPDATE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Automatically update PR
        if: env.PR_UPDATE_TOKEN != ''
        uses: adRise/update-pr-branch@a51c014567e5be98445551cce9b8f5ad42dd8acf # v0.10.2
        with:
          token: ${{ env.PR_UPDATE_TOKEN }}
          base: ${{ github.ref_name }}
          require_auto_merge_enabled: true
          required_approval_count: 1
          require_passed_checks: false
          allow_ongoing_checks: true
          sort: created
          direction: desc

  issue-sync:
    needs:
      - autoupdate
    if: always() && github.event_name == 'push'
    runs-on: ubuntu-slim
    steps:
      - name: Sync issue
        uses: ./.github/actions/workflow/failure-issue
