# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: FOSSA

permissions: {}

on:
  push:
    branches: 
      - main

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: false

jobs:
  analysis:
    name: FOSSA analysis
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run FOSSA analysis
        if: env.FOSSA_API_KEY != ''
        uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # v1.9.0
        with:
          api-key: ${{ env.FOSSA_API_KEY }}

  sync-issue:
    if: always() && github.event_name == 'push'
    needs:
      - analysis
    permissions:
      issues: write
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Sync issue
        uses: ./.github/actions/workflow/failure-issue
        with:
          conclusion: ${{ contains(needs.*.result, 'failure') && 'failure' || job.status }}
          needs: ${{ toJSON(needs) }}
