# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Trivy

permissions: {}

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    - release-*

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Setup Go
      uses: ./.github/actions/go/setup
    - name: Build all
      shell: bash
      run: |
        set -e
        make build-all
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        scan-type: rootfs
        scan-ref: ./cmd/kyverno/kyverno
        format: sarif
        output: kyverno.sarif
        severity: CRITICAL,HIGH
        ignore-unfixed: true
        trivyignores: .trivyignore
    - name: Upload Trivy scan results to GitHub Security
      uses: github/codeql-action/upload-sarif@b1bff81932f5cdfc8695c7752dcee935dcd061c8 # v4
      with:
        sarif_file: kyverno.sarif
        category: kyverno
