# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Verify codegen

permissions: {}

on:
  pull_request:
    branches:
    - main
    - release-*
  merge_group:
    types: [checks_requested]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-codegen-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Go
      uses: ./.github/actions/go/setup
    - name: Generate code
      run:  |
        set -e
        make codegen-all-code
    - name: Verify codegen is up to date
      run:  |
        set -e
        make verify-codegen

  verify-codegen-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Go
      uses: ./.github/actions/go/setup
    - name: Generate api docs
      run:  |
        set -e
        make codegen-all-docs
    - name: Verify codegen is up to date
      run:  |
        set -e
        make verify-codegen

  verify-codegen-success:
    name: verify-codegen
    needs:
      - verify-codegen-code
      - verify-codegen-docs
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - run: ${{ true }}

  verify-codegen-failure:
    name: verify-codegen
    needs:
      - verify-codegen-code
      - verify-codegen-docs
    runs-on: ubuntu-latest
    if: ${{ failure() || cancelled() }}
    steps:
      - run: ${{ false }}
