{
 "title": "Kyverno",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Kyverno\nA Kubernetes-native policy management engine\n\n#### About this dashboard\n\nThis dashboard represents generic insights which can be extracted and made well use of from a cluster with Kyverno in action.\n\n#### For more details around the metrics\n\nCheckout the [official docs of Kyverno metrics](https://kyverno.io/docs/monitoring-kyverno-with-prometheus-metrics/)"
   }
  },
  { "title": "Latest Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Rule Execution Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_results_info{rule_result=\"pass\"})*100/count(kyverno_policy_rule_results_info{})"
    }
   ]
  },
  {
   "title": "Cluster Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"cluster\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"namespaced\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Background Scans Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_results_info{rule_result=\"pass\", policy_background_mode=\"true\"})*100/count(kyverno_policy_rule_results_info{policy_background_mode=\"true\"})"
    }
   ]
  },
  {
   "title": "Validate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"validate\"}==1)"
    }
   ]
  },
  {
   "title": "Mutate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"mutate\"}==1)"
    }
   ]
  },
  {
   "title": "Generate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"generate\"}==1)"
    }
   ]
  },
  { "title": "Policy-Rule Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Admission Review Results (per-rule)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_results_info{rule_execution_cause=\"admission_request\"}) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-rule)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_results_info{rule_execution_cause=\"background_scan\"}) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Policy Failures",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_results_info{rule_result=\"pass\"}) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Admission Review Results (per-policy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_results_info{rule_execution_cause=\"admission_request\"}) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-policy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_results_info{rule_execution_cause=\"background_scan\"}) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  { "title": "Policy-Rule Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Active Policies (by policy type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Policies (by policy validation action)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{}==1) by (policy_name, policy_validation_mode)) by (policy_validation_mode)",
     "legendFormat": "audit"
    }
   ]
  },
  {
   "title": "Active Policies running in background mode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_background_mode=\"true\"}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Namespaced Policies (by namespaces)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_namespace!=\"-\"}==1) by (policy_name, policy_namespace)) by (policy_namespace)",
     "legendFormat": "{{policy_namespace}}"
    }
   ]
  },
  {
   "title": "Active Rules (by rule type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{}==1) by (rule_type)",
     "legendFormat": "{{rule_type}}"
    }
   ]
  },
  { "title": "Policy-Rule Execution Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Average Rule Execution Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg(kyverno_policy_rule_execution_latency_milliseconds{}) by (rule_type)",
     "legendFormat": "{{rule_type}}"
    }
   ]
  },
  {
   "title": "Average Policy Execution Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg(sum(kyverno_policy_rule_execution_latency_milliseconds{}) by (policy_name, policy_execution_timestamp, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Overall Average Rule Execution Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kyverno_policy_rule_execution_latency_milliseconds{})"
    }
   ]
  },
  {
   "title": "Overall Average Policy Execution Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kyverno_policy_rule_execution_latency_milliseconds{}) by (policy_name, policy_execution_timestamp, policy_type))"
    }
   ]
  },
  { "title": "Policy Changes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Policy Changes (by change type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kyverno_policy_changes_info{}) by (policy_change_type)",
     "legendFormat": "Change type: {{policy_change_type}}"
    }
   ]
  },
  {
   "title": "Policy Changes (by policy type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kyverno_policy_changes_info{}) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Overall Policy Changes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_changes_info{})"
    }
   ]
  }
 ]
}