# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Install Cosign
description: Install Cosign

runs:
  using: composite
  steps:
    - uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # v4.1.0
